{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/loadingviewcontroller\/initwithnibname:bundle:"]}],"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithNibName:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"nibNameOrNil"},{"kind":"text","text":" "},{"kind":"identifier","text":"bundle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle","text":"NSBundle"},{"text":" *) ","kind":"text"},{"text":"nibBundleOrNil","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController\/initWithNibName:bundle:"},"kind":"symbol","metadata":{"title":"initWithNibName:bundle:","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"text":"initWithNibName:bundle:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithNibName:bundle:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@App_SIT@objc(cs)LoadingViewController(im)initWithNibName:bundle:","modules":[{"name":"App_SIT"}]},"references":{"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/LoadingViewController/initWithNibName:bundle:":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"role":"symbol","title":"initWithNibName:bundle:","url":"\/documentation\/app_sit\/loadingviewcontroller\/initwithnibname:bundle:","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController\/initWithNibName:bundle:","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithNibName:bundle:","kind":"identifier"}]},"doc://com.example.sit/documentation/App_SIT/LoadingViewController":{"url":"\/documentation\/app_sit\/loadingviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoadingViewController"}],"type":"topic","navigatorTitle":[{"text":"LoadingViewController","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController","role":"symbol","kind":"symbol","title":"LoadingViewController"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LoadingViewController\/title","value":"LoadingViewController"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LoadingViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"LoadingViewController"}]},{"value":[{"text":"LoadingViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LoadingViewController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}