{"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController\/initWithCoder:","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/loadingviewcontroller\/initwithcoder:"]}],"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"role":"symbol","modules":[{"name":"App_SIT"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@App_SIT@objc(cs)LoadingViewController(im)initWithCoder:","roleHeading":"Instance Method","title":"initWithCoder:"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"coder"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"references":{"doc://com.example.sit/documentation/App_SIT/LoadingViewController":{"url":"\/documentation\/app_sit\/loadingviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoadingViewController"}],"type":"topic","navigatorTitle":[{"text":"LoadingViewController","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController","role":"symbol","kind":"symbol","title":"LoadingViewController"},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/LoadingViewController/initWithCoder:":{"title":"initWithCoder:","url":"\/documentation\/app_sit\/loadingviewcontroller\/initwithcoder:","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController\/initWithCoder:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"LoadingViewController","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LoadingViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LoadingViewController\/fragments","value":[{"kind":"identifier","text":"LoadingViewController"}]},{"value":[{"kind":"identifier","text":"LoadingViewController"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LoadingViewController\/navigatorTitle","op":"replace"}]}]}