{"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopLoading"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController\/stopLoading()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/loadingviewcontroller\/stoploading()"]}],"metadata":{"modules":[{"name":"App_SIT"}],"title":"stopLoading()","externalID":"s:7App_SIT21LoadingViewControllerC04stopC0yyF","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"stopLoading","kind":"identifier"},{"kind":"text","text":"()"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method"},"references":{"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/LoadingViewController":{"url":"\/documentation\/app_sit\/loadingviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoadingViewController"}],"type":"topic","navigatorTitle":[{"text":"LoadingViewController","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController","role":"symbol","kind":"symbol","title":"LoadingViewController"},"doc://com.example.sit/documentation/App_SIT/LoadingViewController/stopLoading()":{"abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"stopLoading","kind":"identifier"},{"kind":"text","text":"()"}],"title":"stopLoading()","role":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController\/stopLoading()","url":"\/documentation\/app_sit\/loadingviewcontroller\/stoploading()"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LoadingViewController\/title","op":"replace","value":"LoadingViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LoadingViewController\/fragments","value":[{"kind":"identifier","text":"LoadingViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LoadingViewController\/navigatorTitle","value":[{"kind":"identifier","text":"LoadingViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}