{"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"roleHeading":"Instance Method","title":"viewDidLoad()","externalID":"c:@M@App_SIT@objc(cs)LoadingViewController(im)viewDidLoad","modules":[{"name":"App_SIT"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/loadingviewcontroller\/viewdidload()"]},{"paths":["\/documentation\/app_sit\/loadingviewcontroller\/viewdidload()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController\/viewDidLoad()"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.example.sit/documentation/App_SIT/LoadingViewController/viewDidLoad()":{"abstract":[],"role":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController\/viewDidLoad()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/app_sit\/loadingviewcontroller\/viewdidload()","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"type":"topic"},"doc://com.example.sit/documentation/App_SIT/LoadingViewController":{"url":"\/documentation\/app_sit\/loadingviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoadingViewController"}],"type":"topic","navigatorTitle":[{"text":"LoadingViewController","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController","role":"symbol","kind":"symbol","title":"LoadingViewController"},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"viewDidLoad","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LoadingViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LoadingViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LoadingViewController\/title","op":"replace","value":"LoadingViewController"},{"op":"replace","value":[{"kind":"identifier","text":"LoadingViewController"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LoadingViewController\/fragments"},{"value":[{"kind":"identifier","text":"LoadingViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LoadingViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}