{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/homeRouter","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"homeRouter"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7App_SIT14HomeViewRouterC","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewRouter","kind":"typeIdentifier","text":"HomeViewRouter"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController"]]},"metadata":{"externalID":"s:7App_SIT18HomeViewControllerC10homeRouterAA0cdG0Cvp","role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"homeRouter"},{"kind":"text","text":": "},{"text":"HomeViewRouter","kind":"typeIdentifier","preciseIdentifier":"s:7App_SIT14HomeViewRouterC"}],"title":"homeRouter","modules":[{"name":"App_SIT"}],"symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/homeviewcontroller\/homerouter"]}],"references":{"doc://com.example.sit/documentation/App_SIT/HomeViewRouter":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HomeViewRouter"}],"type":"topic","abstract":[],"role":"symbol","title":"HomeViewRouter","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewRouter","url":"\/documentation\/app_sit\/homeviewrouter","navigatorTitle":[{"kind":"identifier","text":"HomeViewRouter"}],"kind":"symbol"},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/HomeViewController/homeRouter":{"url":"\/documentation\/app_sit\/homeviewcontroller\/homerouter","type":"topic","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/homeRouter","role":"symbol","abstract":[],"kind":"symbol","title":"homeRouter","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"homeRouter","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HomeViewRouter","preciseIdentifier":"s:7App_SIT14HomeViewRouterC"}]},"doc://com.example.sit/documentation/App_SIT/HomeViewController":{"role":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController","navigatorTitle":[{"text":"HomeViewController","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"HomeViewController"},{"text":" class is responsible for managing the home screen of the app.","type":"text"}],"url":"\/documentation\/app_sit\/homeviewcontroller","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HomeViewController","kind":"identifier"}],"title":"HomeViewController","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"HomeViewController","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/title"},{"value":[{"text":"HomeViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"HomeViewController"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}