{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/homeviewcontroller\/initwithnibname:bundle:"]}],"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/initWithNibName:bundle:","interfaceLanguage":"occ"},"sections":[],"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithNibName:bundle:","kind":"identifier"}],"externalID":"c:@M@App_SIT@objc(cs)HomeViewController(im)initWithNibName:bundle:","title":"initWithNibName:bundle:","roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithNibName:bundle:","kind":"identifier"}],"role":"symbol","symbolKind":"method","modules":[{"name":"App_SIT"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithNibName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"nibNameOrNil","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bundle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSBundle","preciseIdentifier":"c:objc(cs)NSBundle"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nibBundleOrNil"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://com.example.sit/documentation/App_SIT":{"kind":"symbol","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","title":"App_SIT","url":"\/documentation\/app_sit"},"doc://com.example.sit/documentation/App_SIT/HomeViewController":{"role":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController","navigatorTitle":[{"text":"HomeViewController","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"HomeViewController"},{"text":" class is responsible for managing the home screen of the app.","type":"text"}],"url":"\/documentation\/app_sit\/homeviewcontroller","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HomeViewController","kind":"identifier"}],"title":"HomeViewController","type":"topic"},"doc://com.example.sit/documentation/App_SIT/HomeViewController/initWithNibName:bundle:":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/initWithNibName:bundle:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithNibName:bundle:","kind":"identifier"}],"url":"\/documentation\/app_sit\/homeviewcontroller\/initwithnibname:bundle:","title":"initWithNibName:bundle:","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/title","value":"HomeViewController","op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/fragments","value":[{"text":"HomeViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/navigatorTitle","value":[{"kind":"identifier","text":"HomeViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}