{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/tableView(_:didSelectRowAt:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/homeviewcontroller\/tableview(_:didselectrowat:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/homeviewcontroller\/tableview(_:didselectrowat:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"tableView"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didSelectRowAt","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"text":": ","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UITableViewDelegate.tableView(_:didSelectRowAt:)"},{"text":".","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController","doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/UITableViewDelegate-Implementations"]]},"sections":[],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"App_SIT"}],"externalID":"c:@CM@App_SIT@objc(cs)HomeViewController(im)tableView:didSelectRowAtIndexPath:","symbolKind":"method","title":"tableView(_:didSelectRowAt:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"tableView:didSelectRowAtIndexPath:"}],"extendedModule":"App_SIT","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectRowAt"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":")"}]},"references":{"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/HomeViewController/UITableViewDelegate-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/UITableViewDelegate-Implementations","abstract":[],"url":"\/documentation\/app_sit\/homeviewcontroller\/uitableviewdelegate-implementations","kind":"article","title":"UITableViewDelegate Implementations","type":"topic"},"doc://com.example.sit/documentation/App_SIT/HomeViewController/tableView(_:didSelectRowAt:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"},{"text":", ","kind":"text"},{"text":"didSelectRowAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"tableView:didSelectRowAtIndexPath:","kind":"identifier"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/tableView(_:didSelectRowAt:)","abstract":[],"kind":"symbol","url":"\/documentation\/app_sit\/homeviewcontroller\/tableview(_:didselectrowat:)","title":"tableView(_:didSelectRowAt:)","role":"symbol"},"doc://com.example.sit/documentation/App_SIT/HomeViewController":{"role":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController","navigatorTitle":[{"text":"HomeViewController","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"HomeViewController"},{"text":" class is responsible for managing the home screen of the app.","type":"text"}],"url":"\/documentation\/app_sit\/homeviewcontroller","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HomeViewController","kind":"identifier"}],"title":"HomeViewController","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"tableView:didSelectRowAtIndexPath:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"tableView:didSelectRowAtIndexPath:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"tableView:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"text":" *) ","kind":"text"},{"text":"tableView","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didSelectRowAtIndexPath:"},{"kind":"text","text":"("},{"text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"indexPath","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController~1tableView(_:didSelectRowAt:)\/title","value":"tableView:didSelectRowAtIndexPath:"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController~1tableView(_:didSelectRowAt:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:didSelectRowAtIndexPath:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/title","value":"HomeViewController"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/fragments","op":"replace","value":[{"text":"HomeViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/navigatorTitle","value":[{"text":"HomeViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}