{"variants":[{"paths":["\/documentation\/app_sit\/homeviewcontroller\/tableview(_:heightforrowat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/homeviewcontroller\/tableview(_:heightforrowat:)"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/tableView(_:heightForRowAt:)"},"metadata":{"extendedModule":"App_SIT","title":"tableView(_:heightForRowAt:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"heightForRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":") -> "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"modules":[{"name":"App_SIT"}],"role":"symbol","externalID":"c:@CM@App_SIT@objc(cs)HomeViewController(im)tableView:heightForRowAtIndexPath:","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"tableView:heightForRowAtIndexPath:"}]},"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController","doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/UITableViewDelegate-Implementations"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UITableViewDelegate.tableView(_:heightForRowAt:)"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":": "},{"text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"heightForRowAt","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"languages":["swift"]}]}],"references":{"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/HomeViewController":{"role":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController","navigatorTitle":[{"text":"HomeViewController","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"HomeViewController"},{"text":" class is responsible for managing the home screen of the app.","type":"text"}],"url":"\/documentation\/app_sit\/homeviewcontroller","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HomeViewController","kind":"identifier"}],"title":"HomeViewController","type":"topic"},"doc://com.example.sit/documentation/App_SIT/HomeViewController/tableView(_:heightForRowAt:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"heightForRowAt"},{"text":": ","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"navigatorTitle":[{"kind":"identifier","text":"tableView:heightForRowAtIndexPath:"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/tableView(_:heightForRowAt:)","abstract":[],"url":"\/documentation\/app_sit\/homeviewcontroller\/tableview(_:heightforrowat:)","kind":"symbol","title":"tableView(_:heightForRowAt:)","role":"symbol"},"doc://com.example.sit/documentation/App_SIT/HomeViewController/UITableViewDelegate-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/UITableViewDelegate-Implementations","abstract":[],"url":"\/documentation\/app_sit\/homeviewcontroller\/uitableviewdelegate-implementations","kind":"article","title":"UITableViewDelegate Implementations","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"tableView:heightForRowAtIndexPath:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"tableView:heightForRowAtIndexPath:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat"},{"text":") ","kind":"text"},{"text":"tableView:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":" "},{"text":"heightForRowAtIndexPath:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSIndexPath","kind":"typeIdentifier","text":"NSIndexPath"},{"text":" *) ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"HomeViewController","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/title"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"HomeViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/navigatorTitle","value":[{"text":"HomeViewController","kind":"identifier"}]},{"op":"replace","value":"tableView:heightForRowAtIndexPath:","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController~1tableView(_:heightForRowAt:)\/title"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController~1tableView(_:heightForRowAt:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"tableView:heightForRowAtIndexPath:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}