{"variants":[{"paths":["\/documentation\/app_sit\/homeviewcontroller\/tableview(_:numberofrowsinsection:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/homeviewcontroller\/tableview(_:numberofrowsinsection:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/tableView(_:numberOfRowsInSection:)","interfaceLanguage":"swift"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UITableViewDataSource.tableView(_:numberOfRowsInSection:)","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"tableView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfRowsInSection"},{"kind":"text","text":" "},{"text":"section","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]}]}],"metadata":{"externalID":"c:@CM@App_SIT@objc(cs)HomeViewController(im)tableView:numberOfRowsInSection:","modules":[{"name":"App_SIT"}],"extendedModule":"App_SIT","symbolKind":"method","title":"tableView(_:numberOfRowsInSection:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier","text":"UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfRowsInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":") -> ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"tableView:numberOfRowsInSection:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController","doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/UITableViewDataSource-Implementations"]]},"references":{"doc://com.example.sit/documentation/App_SIT/HomeViewController":{"role":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController","navigatorTitle":[{"text":"HomeViewController","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"HomeViewController"},{"text":" class is responsible for managing the home screen of the app.","type":"text"}],"url":"\/documentation\/app_sit\/homeviewcontroller","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HomeViewController","kind":"identifier"}],"title":"HomeViewController","type":"topic"},"doc://com.example.sit/documentation/App_SIT/HomeViewController/tableView(_:numberOfRowsInSection:)":{"title":"tableView(_:numberOfRowsInSection:)","navigatorTitle":[{"text":"tableView:numberOfRowsInSection:","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"text":", ","kind":"text"},{"text":"numberOfRowsInSection","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/tableView(_:numberOfRowsInSection:)","url":"\/documentation\/app_sit\/homeviewcontroller\/tableview(_:numberofrowsinsection:)","role":"symbol"},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/HomeViewController/UITableViewDataSource-Implementations":{"title":"UITableViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/UITableViewDataSource-Implementations","url":"\/documentation\/app_sit\/homeviewcontroller\/uitableviewdatasource-implementations","role":"collectionGroup","kind":"article","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"tableView:numberOfRowsInSection:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":") ","kind":"text"},{"text":"tableView:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"text":" *) ","kind":"text"},{"text":"tableView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"numberOfRowsInSection:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"text":"section","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"HomeViewController","op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/fragments","value":[{"kind":"identifier","text":"HomeViewController"}]},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"HomeViewController"}]},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController~1tableView(_:numberOfRowsInSection:)\/title","op":"replace","value":"tableView:numberOfRowsInSection:"},{"value":[{"text":"- ","kind":"text"},{"text":"tableView:numberOfRowsInSection:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController~1tableView(_:numberOfRowsInSection:)\/fragments"}]}]}