{"kind":"symbol","metadata":{"externalID":"c:@M@App_SIT@objc(cs)HomeViewController(py)tableView","modules":[{"name":"App_SIT"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"kind":"text","text":": "},{"text":"BaseTableView","preciseIdentifier":"c:@M@App_SIT@objc(cs)BaseTableView","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"title":"tableView","navigatorTitle":[{"text":"tableView","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"weak"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@App_SIT@objc(cs)BaseTableView","text":"BaseTableView","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView"},{"kind":"text","text":"!"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController"]]},"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/tableView","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/homeviewcontroller\/tableview"]},{"paths":["\/documentation\/app_sit\/homeviewcontroller\/tableview"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/BaseTableView":{"type":"topic","abstract":[],"url":"\/documentation\/app_sit\/basetableview","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView","navigatorTitle":[{"text":"BaseTableView","kind":"identifier"}],"title":"BaseTableView","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BaseTableView"}]},"doc://com.example.sit/documentation/App_SIT/HomeViewController":{"role":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController","navigatorTitle":[{"text":"HomeViewController","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"HomeViewController"},{"text":" class is responsible for managing the home screen of the app.","type":"text"}],"url":"\/documentation\/app_sit\/homeviewcontroller","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HomeViewController","kind":"identifier"}],"title":"HomeViewController","type":"topic"},"doc://com.example.sit/documentation/App_SIT/HomeViewController/tableView":{"title":"tableView","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/tableView","abstract":[],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@App_SIT@objc(cs)BaseTableView","text":"BaseTableView"},{"text":"!","kind":"text"}],"url":"\/documentation\/app_sit\/homeviewcontroller\/tableview","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"tableView"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"tableView"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"tableView"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"BaseTableView","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView","preciseIdentifier":"c:@M@App_SIT@objc(cs)BaseTableView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"BaseTableView","op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView\/title"},{"value":[{"text":"BaseTableView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView\/fragments"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView\/navigatorTitle","op":"replace","value":[{"text":"BaseTableView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/title","op":"replace","value":"HomeViewController"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/fragments","op":"replace","value":[{"text":"HomeViewController","kind":"identifier"}]},{"value":[{"text":"HomeViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController~1tableView\/title","value":"tableView"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController~1tableView\/fragments","op":"replace","value":[{"text":"tableView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}