{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellForRowAt"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"navigatorTitle":[{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}],"symbolKind":"method","externalID":"c:@CM@App_SIT@objc(cs)HomeViewController(im)tableView:cellForRowAtIndexPath:","extendedModule":"App_SIT","roleHeading":"Instance Method","modules":[{"name":"App_SIT"}],"role":"symbol","title":"tableView(_:cellForRowAt:)"},"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController","doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/UITableViewDataSource-Implementations"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/tableView(_:cellForRowAt:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier","text":"UITableView"},{"text":", ","kind":"text"},{"text":"cellForRowAt","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell","kind":"typeIdentifier"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"code":"UITableViewDataSource.tableView(_:cellForRowAt:)","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/homeviewcontroller\/tableview(_:cellforrowat:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/homeviewcontroller\/tableview(_:cellforrowat:)"]}],"references":{"doc://com.example.sit/documentation/App_SIT/HomeViewController":{"role":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController","navigatorTitle":[{"text":"HomeViewController","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"HomeViewController"},{"text":" class is responsible for managing the home screen of the app.","type":"text"}],"url":"\/documentation\/app_sit\/homeviewcontroller","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HomeViewController","kind":"identifier"}],"title":"HomeViewController","type":"topic"},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/HomeViewController/UITableViewDataSource-Implementations":{"title":"UITableViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/UITableViewDataSource-Implementations","url":"\/documentation\/app_sit\/homeviewcontroller\/uitableviewdatasource-implementations","role":"collectionGroup","kind":"article","type":"topic"},"doc://com.example.sit/documentation/App_SIT/HomeViewController/tableView(_:cellForRowAt:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"},{"text":", ","kind":"text"},{"text":"cellForRowAt","kind":"externalParam"},{"kind":"text","text":": "},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"navigatorTitle":[{"text":"tableView:cellForRowAtIndexPath:","kind":"identifier"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/tableView(_:cellForRowAt:)","type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/app_sit\/homeviewcontroller\/tableview(_:cellforrowat:)","title":"tableView(_:cellForRowAt:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"tableView:cellForRowAtIndexPath:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"UITableViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"tableView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"},{"text":" *) ","kind":"text"},{"text":"tableView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cellForRowAtIndexPath:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSIndexPath","text":"NSIndexPath","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"indexPath"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/title","value":"HomeViewController"},{"value":[{"text":"HomeViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/navigatorTitle","value":[{"text":"HomeViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController~1tableView(_:cellForRowAt:)\/title","value":"tableView:cellForRowAtIndexPath:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"tableView:cellForRowAtIndexPath:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController~1tableView(_:cellForRowAt:)\/fragments"}]}]}