{"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/featureoneviewcontroller\/initwithnibname:bundle:"]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController\/initWithNibName:bundle:","interfaceLanguage":"occ"},"metadata":{"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"modules":[{"name":"App_SIT"}],"title":"initWithNibName:bundle:","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"externalID":"c:@M@App_SIT@objc(cs)FeatureOneViewController(im)initWithNibName:bundle:"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"text":"initWithNibName:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nibNameOrNil"},{"kind":"text","text":" "},{"kind":"identifier","text":"bundle:"},{"text":"(","kind":"text"},{"text":"NSBundle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle"},{"text":" *) ","kind":"text"},{"text":"nibBundleOrNil","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"references":{"doc://com.example.sit/documentation/App_SIT/FeatureOneViewController/initWithNibName:bundle:":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController\/initWithNibName:bundle:","type":"topic","navigatorTitle":[{"text":"initWithNibName:bundle:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"url":"\/documentation\/app_sit\/featureoneviewcontroller\/initwithnibname:bundle:","title":"initWithNibName:bundle:","role":"symbol"},"doc://com.example.sit/documentation/App_SIT/FeatureOneViewController":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController","type":"topic","navigatorTitle":[{"text":"FeatureOneViewController","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FeatureOneViewController","kind":"identifier"}],"abstract":[],"url":"\/documentation\/app_sit\/featureoneviewcontroller","title":"FeatureOneViewController","role":"symbol"},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1FeatureOneViewController\/title","value":"FeatureOneViewController","op":"replace"},{"value":[{"kind":"identifier","text":"FeatureOneViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1FeatureOneViewController\/fragments"},{"value":[{"text":"FeatureOneViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1FeatureOneViewController\/navigatorTitle"}]}]}