{"metadata":{"title":"initWithCoder:","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"externalID":"c:@M@App_SIT@objc(cs)FeatureOneViewController(im)initWithCoder:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"modules":[{"name":"App_SIT"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController\/initWithCoder:"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/app_sit\/featureoneviewcontroller\/initwithcoder:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"coder"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"references":{"doc://com.example.sit/documentation/App_SIT/FeatureOneViewController":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController","type":"topic","navigatorTitle":[{"text":"FeatureOneViewController","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FeatureOneViewController","kind":"identifier"}],"abstract":[],"url":"\/documentation\/app_sit\/featureoneviewcontroller","title":"FeatureOneViewController","role":"symbol"},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/FeatureOneViewController/initWithCoder:":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController\/initWithCoder:","type":"topic","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"url":"\/documentation\/app_sit\/featureoneviewcontroller\/initwithcoder:","title":"initWithCoder:","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1FeatureOneViewController\/title","op":"replace","value":"FeatureOneViewController"},{"op":"replace","value":[{"kind":"identifier","text":"FeatureOneViewController"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1FeatureOneViewController\/fragments"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1FeatureOneViewController\/navigatorTitle","value":[{"kind":"identifier","text":"FeatureOneViewController"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}