{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"externalID":"c:@M@App_SIT@objc(cs)FeatureOneViewController(im)viewDidLoad","roleHeading":"Instance Method","title":"viewDidLoad()","modules":[{"name":"App_SIT"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"text":"()","kind":"text"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController\/viewDidLoad()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/featureoneviewcontroller\/viewdidload()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/featureoneviewcontroller\/viewdidload()"]}],"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController"]]},"kind":"symbol","references":{"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/FeatureOneViewController":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController","type":"topic","navigatorTitle":[{"text":"FeatureOneViewController","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FeatureOneViewController","kind":"identifier"}],"abstract":[],"url":"\/documentation\/app_sit\/featureoneviewcontroller","title":"FeatureOneViewController","role":"symbol"},"doc://com.example.sit/documentation/App_SIT/FeatureOneViewController/viewDidLoad()":{"role":"symbol","abstract":[],"navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"title":"viewDidLoad()","type":"topic","url":"\/documentation\/app_sit\/featureoneviewcontroller\/viewdidload()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController\/viewDidLoad()","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"viewDidLoad"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"viewDidLoad","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"FeatureOneViewController","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1FeatureOneViewController\/title"},{"value":[{"text":"FeatureOneViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1FeatureOneViewController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1FeatureOneViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"FeatureOneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1FeatureOneViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1FeatureOneViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}