{"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/sceneDidDisconnect(_:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sceneDidDisconnect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"scene","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIScene","kind":"typeIdentifier","text":"UIScene"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","platforms":[{"unavailable":false,"introducedAt":"13.0","name":"iOS","beta":false,"deprecated":false},{"beta":false,"name":"iPadOS","introducedAt":"13.0","deprecated":false,"unavailable":false},{"beta":false,"unavailable":false,"deprecated":false,"introducedAt":"13.0","name":"Mac Catalyst"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sceneDidDisconnect","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIScene","kind":"typeIdentifier","text":"UIScene"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"sceneDidDisconnect:"}],"symbolKind":"method","externalID":"c:@M@App_SIT@objc(cs)SceneDelegate(im)sceneDidDisconnect:","title":"sceneDidDisconnect(_:)","modules":[{"name":"App_SIT"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Inherited from "},{"code":"UISceneDelegate.sceneDidDisconnect(_:)","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/app_sit\/scenedelegate\/scenediddisconnect(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/app_sit\/scenedelegate\/scenediddisconnect(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/SceneDelegate/sceneDidDisconnect(_:)":{"title":"sceneDidDisconnect(_:)","kind":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/sceneDidDisconnect(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sceneDidDisconnect","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIScene","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":")"}],"url":"\/documentation\/app_sit\/scenedelegate\/scenediddisconnect(_:)","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"text":"sceneDidDisconnect:","kind":"identifier"}]},"doc://com.example.sit/documentation/App_SIT/SceneDelegate":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate","url":"\/documentation\/app_sit\/scenedelegate","kind":"symbol","title":"SceneDelegate","role":"symbol","navigatorTitle":[{"text":"SceneDelegate","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SceneDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"sceneDidDisconnect:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sceneDidDisconnect:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"sceneDidDisconnect:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIScene","kind":"typeIdentifier","text":"UIScene"},{"text":" *) ","kind":"text"},{"text":"scene","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"sceneDidDisconnect:","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate~1sceneDidDisconnect(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate~1sceneDidDisconnect(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sceneDidDisconnect:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate\/title","value":"SceneDelegate"},{"value":[{"text":"SceneDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SceneDelegate"}],"op":"replace"}]}]}