{"variants":[{"paths":["\/documentation\/app_sit\/scenedelegate\/scenedidbecomeactive(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/scenedelegate\/scenedidbecomeactive(_:)"]}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sceneDidBecomeActive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"scene"},{"kind":"text","text":": "},{"text":"UIScene","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScene"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@App_SIT@objc(cs)SceneDelegate(im)sceneDidBecomeActive:","platforms":[{"beta":false,"name":"iOS","deprecated":false,"introducedAt":"13.0","unavailable":false},{"introducedAt":"13.0","deprecated":false,"beta":false,"name":"iPadOS","unavailable":false},{"introducedAt":"13.0","beta":false,"deprecated":false,"unavailable":false,"name":"Mac Catalyst"}],"symbolKind":"method","role":"symbol","modules":[{"name":"App_SIT"}],"title":"sceneDidBecomeActive(_:)","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sceneDidBecomeActive"},{"kind":"text","text":"("},{"text":"UIScene","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScene"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"sceneDidBecomeActive:"}]},"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate"]]},"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/sceneDidBecomeActive(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UISceneDelegate.sceneDidBecomeActive(_:)"},{"text":".","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.example.sit/documentation/App_SIT/SceneDelegate/sceneDidBecomeActive(_:)":{"title":"sceneDidBecomeActive(_:)","kind":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/sceneDidBecomeActive(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sceneDidBecomeActive","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIScene","text":"UIScene","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/app_sit\/scenedelegate\/scenedidbecomeactive(_:)","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sceneDidBecomeActive:"}]},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/SceneDelegate":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate","url":"\/documentation\/app_sit\/scenedelegate","kind":"symbol","title":"SceneDelegate","role":"symbol","navigatorTitle":[{"text":"SceneDelegate","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SceneDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"sceneDidBecomeActive:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sceneDidBecomeActive:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"sceneDidBecomeActive:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIScene","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"scene"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"sceneDidBecomeActive:","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate~1sceneDidBecomeActive(_:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"sceneDidBecomeActive:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate~1sceneDidBecomeActive(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate\/title","value":"SceneDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate\/fragments","value":[{"text":"SceneDelegate","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SceneDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate\/navigatorTitle"}]}]}