{"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate"]]},"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"scene:willConnectToSession:options:","kind":"identifier"}],"platforms":[{"introducedAt":"13.0","deprecated":false,"name":"iOS","unavailable":false,"beta":false},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"13.0","name":"iPadOS"},{"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.0","beta":false,"deprecated":false}],"modules":[{"name":"App_SIT"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"scene","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScene","preciseIdentifier":"c:objc(cs)UIScene"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"willConnectTo"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UISceneSession","text":"UISceneSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"text":"UIScene","preciseIdentifier":"c:objc(cs)UIScene","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISceneConnectionOptions","text":"ConnectionOptions"},{"kind":"text","text":")"}],"title":"scene(_:willConnectTo:options:)","role":"symbol","symbolKind":"method","externalID":"c:@M@App_SIT@objc(cs)SceneDelegate(im)scene:willConnectToSession:options:"},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/scene(_:willConnectTo:options:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UISceneDelegate.scene(_:willConnectTo:options:)"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/scenedelegate\/scene(_:willconnectto:options:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/scenedelegate\/scene(_:willconnectto:options:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"scene","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"scene"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIScene","text":"UIScene","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willConnectTo"},{"text":" ","kind":"text"},{"text":"session","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UISceneSession","kind":"typeIdentifier","text":"UISceneSession"},{"kind":"text","text":", "},{"text":"options","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"connectionOptions"},{"kind":"text","text":": "},{"text":"UIScene","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":"."},{"text":"ConnectionOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISceneConnectionOptions"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/SceneDelegate":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate","url":"\/documentation\/app_sit\/scenedelegate","kind":"symbol","title":"SceneDelegate","role":"symbol","navigatorTitle":[{"text":"SceneDelegate","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SceneDelegate","kind":"identifier"}]},"doc://com.example.sit/documentation/App_SIT/SceneDelegate/scene(_:willConnectTo:options:)":{"abstract":[],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/scene(_:willConnectTo:options:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scene","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIScene","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScene"},{"text":", ","kind":"text"},{"text":"willConnectTo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UISceneSession","kind":"typeIdentifier","text":"UISceneSession"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIScene","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":"."},{"preciseIdentifier":"c:objc(cs)UISceneConnectionOptions","text":"ConnectionOptions","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"scene:willConnectToSession:options:"}],"title":"scene(_:willConnectTo:options:)","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/app_sit\/scenedelegate\/scene(_:willconnectto:options:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"scene:willConnectToSession:options:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scene:willConnectToSession:options:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"scene:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScene","text":"UIScene"},{"text":" *) ","kind":"text"},{"text":"scene","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"willConnectToSession:"},{"text":"(","kind":"text"},{"text":"UISceneSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISceneSession"},{"text":" *) ","kind":"text"},{"text":"session","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"options:"},{"kind":"text","text":"("},{"text":"UISceneConnectionOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISceneConnectionOptions"},{"kind":"text","text":" *) "},{"text":"connectionOptions","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate\/title","value":"SceneDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate\/fragments","value":[{"kind":"identifier","text":"SceneDelegate"}]},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate\/navigatorTitle","value":[{"text":"SceneDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate~1scene(_:willConnectTo:options:)\/title","value":"scene:willConnectToSession:options:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate~1scene(_:willConnectTo:options:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"scene:willConnectToSession:options:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}