{"metadata":{"externalID":"c:@M@App_SIT@objc(cs)SceneDelegate(im)sceneDidEnterBackground:","title":"sceneDidEnterBackground(_:)","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"sceneDidEnterBackground:","kind":"identifier"}],"modules":[{"name":"App_SIT"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sceneDidEnterBackground","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScene","text":"UIScene"},{"kind":"text","text":")"}],"platforms":[{"name":"iOS","introducedAt":"13.0","beta":false,"deprecated":false,"unavailable":false},{"name":"iPadOS","introducedAt":"13.0","unavailable":false,"beta":false,"deprecated":false},{"beta":false,"introducedAt":"13.0","name":"Mac Catalyst","unavailable":false,"deprecated":false}]},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UISceneDelegate.sceneDidEnterBackground(_:)"},{"text":".","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/sceneDidEnterBackground(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sceneDidEnterBackground","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"scene"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIScene","text":"UIScene","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/scenedelegate\/scenedidenterbackground(_:)"]},{"paths":["\/documentation\/app_sit\/scenedelegate\/scenedidenterbackground(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate"]]},"references":{"doc://com.example.sit/documentation/App_SIT/SceneDelegate":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate","url":"\/documentation\/app_sit\/scenedelegate","kind":"symbol","title":"SceneDelegate","role":"symbol","navigatorTitle":[{"text":"SceneDelegate","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SceneDelegate","kind":"identifier"}]},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/SceneDelegate/sceneDidEnterBackground(_:)":{"kind":"symbol","url":"\/documentation\/app_sit\/scenedelegate\/scenedidenterbackground(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sceneDidEnterBackground","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIScene","preciseIdentifier":"c:objc(cs)UIScene"},{"text":")","kind":"text"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"sceneDidEnterBackground:"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/sceneDidEnterBackground(_:)","type":"topic","title":"sceneDidEnterBackground(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"sceneDidEnterBackground:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"sceneDidEnterBackground:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"sceneDidEnterBackground:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIScene","text":"UIScene","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"scene"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"SceneDelegate","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate\/fragments","value":[{"kind":"identifier","text":"SceneDelegate"}]},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate\/navigatorTitle","value":[{"text":"SceneDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate~1sceneDidEnterBackground(_:)\/title","value":"sceneDidEnterBackground:"},{"value":[{"text":"- ","kind":"text"},{"text":"sceneDidEnterBackground:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate~1sceneDidEnterBackground(_:)\/fragments"}]}]}