{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sceneWillResignActive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"scene","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIScene","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":")"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"text":"sceneWillResignActive:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","title":"sceneWillResignActive(_:)","externalID":"c:@M@App_SIT@objc(cs)SceneDelegate(im)sceneWillResignActive:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sceneWillResignActive"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIScene","text":"UIScene","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":[{"beta":false,"name":"iOS","unavailable":false,"deprecated":false,"introducedAt":"13.0"},{"deprecated":false,"name":"iPadOS","introducedAt":"13.0","beta":false,"unavailable":false},{"introducedAt":"13.0","unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false}],"modules":[{"name":"App_SIT"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/sceneWillResignActive(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UISceneDelegate.sceneWillResignActive(_:)"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/scenedelegate\/scenewillresignactive(_:)"]},{"paths":["\/documentation\/app_sit\/scenedelegate\/scenewillresignactive(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/SceneDelegate/sceneWillResignActive(_:)":{"title":"sceneWillResignActive(_:)","kind":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/sceneWillResignActive(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sceneWillResignActive","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIScene","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":")"}],"url":"\/documentation\/app_sit\/scenedelegate\/scenewillresignactive(_:)","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"text":"sceneWillResignActive:","kind":"identifier"}]},"doc://com.example.sit/documentation/App_SIT/SceneDelegate":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate","url":"\/documentation\/app_sit\/scenedelegate","kind":"symbol","title":"SceneDelegate","role":"symbol","navigatorTitle":[{"text":"SceneDelegate","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SceneDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"sceneWillResignActive:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"sceneWillResignActive:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"sceneWillResignActive:"},{"text":"(","kind":"text"},{"text":"UIScene","preciseIdentifier":"c:objc(cs)UIScene","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"scene","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate~1sceneWillResignActive(_:)\/title","value":"sceneWillResignActive:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate~1sceneWillResignActive(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sceneWillResignActive:"}]},{"op":"replace","value":"SceneDelegate","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate\/title"},{"value":[{"kind":"identifier","text":"SceneDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate\/navigatorTitle","op":"replace","value":[{"text":"SceneDelegate","kind":"identifier"}]}]}]}