{"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIWindowSceneDelegate.window"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"window","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIWindow","kind":"typeIdentifier","text":"UIWindow"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/app_sit\/scenedelegate\/window"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/scenedelegate\/window"]}],"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate"]]},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"window"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIWindow","text":"UIWindow"},{"kind":"text","text":"?"}],"platforms":[{"introducedAt":"13.0","deprecated":false,"beta":false,"name":"iOS","unavailable":false},{"introducedAt":"13.0","name":"iPadOS","deprecated":false,"beta":false,"unavailable":false},{"introducedAt":"13.0","beta":false,"deprecated":false,"name":"Mac Catalyst","unavailable":false}],"symbolKind":"property","role":"symbol","title":"window","navigatorTitle":[{"text":"window","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"App_SIT"}],"externalID":"c:@M@App_SIT@objc(cs)SceneDelegate(py)window"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/window"},"references":{"doc://com.example.sit/documentation/App_SIT/SceneDelegate/window":{"title":"window","kind":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/window","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"window","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIWindow","text":"UIWindow","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/app_sit\/scenedelegate\/window","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"window"}]},"doc://com.example.sit/documentation/App_SIT/SceneDelegate":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate","url":"\/documentation\/app_sit\/scenedelegate","kind":"symbol","title":"SceneDelegate","role":"symbol","navigatorTitle":[{"text":"SceneDelegate","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SceneDelegate","kind":"identifier"}]},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"window","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"window"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"window","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate~1window\/title","value":"window"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate~1window\/fragments","op":"replace","value":[{"kind":"identifier","text":"window"}]},{"op":"replace","value":"SceneDelegate","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate\/title"},{"op":"replace","value":[{"text":"SceneDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate\/navigatorTitle","value":[{"text":"SceneDelegate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}