{"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell\/awakeFromNib()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"awakeFromNib","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell"]]},"variants":[{"paths":["\/documentation\/app_sit\/testingviewcell\/awakefromnib()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/app_sit\/testingviewcell\/awakefromnib()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"awakeFromNib","kind":"identifier"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:@M@App_SIT@objc(cs)TestingViewCell(im)awakeFromNib","modules":[{"name":"App_SIT"}],"role":"symbol","title":"awakeFromNib()","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"awakeFromNib"}]},"references":{"doc://com.example.sit/documentation/App_SIT/TestingViewCell/awakeFromNib()":{"kind":"symbol","abstract":[],"title":"awakeFromNib()","type":"topic","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell\/awakeFromNib()","url":"\/documentation\/app_sit\/testingviewcell\/awakefromnib()","role":"symbol","navigatorTitle":[{"text":"awakeFromNib","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"awakeFromNib"},{"kind":"text","text":"()"}]},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/TestingViewCell":{"navigatorTitle":[{"kind":"identifier","text":"TestingViewCell"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TestingViewCell","kind":"identifier"}],"url":"\/documentation\/app_sit\/testingviewcell","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell","title":"TestingViewCell","type":"topic","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"awakeFromNib"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"awakeFromNib"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"awakeFromNib"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"awakeFromNib","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell~1awakeFromNib()\/title"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell~1awakeFromNib()\/fragments","value":[{"kind":"text","text":"- "},{"text":"awakeFromNib","kind":"identifier"}],"op":"replace"},{"value":"TestingViewCell","op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell\/title"},{"value":[{"text":"TestingViewCell","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell\/fragments"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell\/navigatorTitle","value":[{"text":"TestingViewCell","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}