{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/testingviewcell\/config(name:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell\/config(name:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"config","kind":"identifier"},{"text":"(","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"config(name:)","roleHeading":"Instance Method","symbolKind":"method","role":"symbol","modules":[{"name":"App_SIT"}],"externalID":"s:7App_SIT15TestingViewCellC6config4nameySS_tF"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"config","kind":"identifier"},{"text":"(","kind":"text"},{"text":"name","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell"]]},"references":{"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/TestingViewCell/config(name:)":{"url":"\/documentation\/app_sit\/testingviewcell\/config(name:)","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell\/config(name:)","role":"symbol","kind":"symbol","type":"topic","title":"config(name:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"config","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.example.sit/documentation/App_SIT/TestingViewCell":{"navigatorTitle":[{"kind":"identifier","text":"TestingViewCell"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TestingViewCell","kind":"identifier"}],"url":"\/documentation\/app_sit\/testingviewcell","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell","title":"TestingViewCell","type":"topic","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"TestingViewCell","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell\/fragments","op":"replace","value":[{"text":"TestingViewCell","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell\/navigatorTitle","value":[{"kind":"identifier","text":"TestingViewCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}