{"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell\/initWithCoder:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/testingviewcell\/initwithcoder:"]}],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}],"externalID":"c:@M@App_SIT@objc(cs)TestingViewCell(im)initWithCoder:","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"modules":[{"name":"App_SIT"}],"title":"initWithCoder:","role":"symbol"},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"text":" *) ","kind":"text"},{"text":"coder","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"references":{"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/TestingViewCell":{"navigatorTitle":[{"kind":"identifier","text":"TestingViewCell"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TestingViewCell","kind":"identifier"}],"url":"\/documentation\/app_sit\/testingviewcell","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell","title":"TestingViewCell","type":"topic","abstract":[],"kind":"symbol"},"doc://com.example.sit/documentation/App_SIT/TestingViewCell/initWithCoder:":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell\/initWithCoder:","type":"topic","role":"symbol","title":"initWithCoder:","url":"\/documentation\/app_sit\/testingviewcell\/initwithcoder:","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"kind":"symbol","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"TestingViewCell","op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell\/title"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell\/fragments","op":"replace","value":[{"text":"TestingViewCell","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"TestingViewCell"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}