{"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell\/initWithStyle:reuseIdentifier:"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"text":"initWithStyle:reuseIdentifier:","kind":"identifier"}],"role":"symbol","platforms":[{"introducedAt":"3.0","deprecated":false,"beta":false,"name":"iOS","unavailable":false},{"name":"iPadOS","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"3.0"},{"beta":false,"deprecated":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"3.0"}],"roleHeading":"Instance Method","title":"initWithStyle:reuseIdentifier:","symbolKind":"method","externalID":"c:@M@App_SIT@objc(cs)TestingViewCell(im)initWithStyle:reuseIdentifier:","modules":[{"name":"App_SIT"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithStyle:reuseIdentifier:","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithStyle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@UITableViewCellStyle","kind":"typeIdentifier","text":"UITableViewCellStyle"},{"text":") ","kind":"text"},{"text":"style","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reuseIdentifier:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reuseIdentifier","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/testingviewcell\/initwithstyle:reuseidentifier:"]}],"references":{"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/TestingViewCell/initWithStyle:reuseIdentifier:":{"title":"initWithStyle:reuseIdentifier:","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithStyle:reuseIdentifier:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell\/initWithStyle:reuseIdentifier:","kind":"symbol","navigatorTitle":[{"text":"initWithStyle:reuseIdentifier:","kind":"identifier"}],"type":"topic","url":"\/documentation\/app_sit\/testingviewcell\/initwithstyle:reuseidentifier:"},"doc://com.example.sit/documentation/App_SIT/TestingViewCell":{"navigatorTitle":[{"kind":"identifier","text":"TestingViewCell"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TestingViewCell","kind":"identifier"}],"url":"\/documentation\/app_sit\/testingviewcell","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell","title":"TestingViewCell","type":"topic","abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TestingViewCell","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell\/title","op":"replace"},{"value":[{"text":"TestingViewCell","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell\/fragments"},{"value":[{"text":"TestingViewCell","kind":"identifier"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell\/navigatorTitle","op":"replace"}]}]}