{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell\/nameLabel"},"metadata":{"modules":[{"name":"App_SIT"}],"role":"symbol","symbolKind":"property","title":"nameLabel","externalID":"c:@M@App_SIT@objc(cs)TestingViewCell(py)nameLabel","navigatorTitle":[{"text":"nameLabel","kind":"identifier"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"nameLabel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"},{"text":"!","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/testingviewcell\/namelabel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/testingviewcell\/namelabel"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@IBOutlet","kind":"attribute"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nameLabel"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel","kind":"typeIdentifier"},{"text":"!","kind":"text"}]}]}],"references":{"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/TestingViewCell":{"navigatorTitle":[{"kind":"identifier","text":"TestingViewCell"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TestingViewCell","kind":"identifier"}],"url":"\/documentation\/app_sit\/testingviewcell","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell","title":"TestingViewCell","type":"topic","abstract":[],"kind":"symbol"},"doc://com.example.sit/documentation/App_SIT/TestingViewCell/nameLabel":{"kind":"symbol","abstract":[],"url":"\/documentation\/app_sit\/testingviewcell\/namelabel","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell\/nameLabel","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nameLabel"},{"text":": ","kind":"text"},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"},{"text":"!","kind":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"nameLabel","kind":"identifier"}],"title":"nameLabel"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"nameLabel","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"nameLabel","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"kind":"text","text":") "},{"text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"nameLabel","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell\/title","value":"TestingViewCell","op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell\/fragments","value":[{"kind":"identifier","text":"TestingViewCell"}],"op":"replace"},{"op":"replace","value":[{"text":"TestingViewCell","kind":"identifier"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell~1nameLabel\/title","value":"nameLabel","op":"replace"},{"value":[{"text":"nameLabel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell~1nameLabel\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}