{"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell"]]},"sections":[],"variants":[{"paths":["\/documentation\/app_sit\/testingviewcell\/setselected(_:animated:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/app_sit\/testingviewcell\/setselected(_:animated:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell\/setSelected(_:animated:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"App_SIT"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setSelected","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"animated","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","externalID":"c:@M@App_SIT@objc(cs)TestingViewCell(im)setSelected:animated:","title":"setSelected(_:animated:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setSelected:animated:"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setSelected","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"selected","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.example.sit/documentation/App_SIT/TestingViewCell/setSelected(_:animated:)":{"type":"topic","url":"\/documentation\/app_sit\/testingviewcell\/setselected(_:animated:)","title":"setSelected(_:animated:)","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"setSelected:animated:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setSelected"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell\/setSelected(_:animated:)"},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/TestingViewCell":{"navigatorTitle":[{"kind":"identifier","text":"TestingViewCell"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TestingViewCell","kind":"identifier"}],"url":"\/documentation\/app_sit\/testingviewcell","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell","title":"TestingViewCell","type":"topic","abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"setSelected:animated:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setSelected:animated:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setSelected:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"selected"},{"text":" ","kind":"text"},{"text":"animated:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"animated","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell~1setSelected(_:animated:)\/title","value":"setSelected:animated:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell~1setSelected(_:animated:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setSelected:animated:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell\/title","value":"TestingViewCell","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell\/fragments","value":[{"kind":"identifier","text":"TestingViewCell"}]},{"op":"replace","value":[{"kind":"identifier","text":"TestingViewCell"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell\/navigatorTitle"}]}]}