{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@main"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppDelegate"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.example.sit\/objc(cs)UIResponder"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.example.sit\/objc(pl)NSObject","doc:\/\/com.example.sit\/s7CVarArgP","doc:\/\/com.example.sit\/s28CustomDebugStringConvertibleP","doc:\/\/com.example.sit\/s23CustomStringConvertibleP","doc:\/\/com.example.sit\/SQ","doc:\/\/com.example.sit\/SH","doc:\/\/com.example.sit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.example.sit\/objc(pl)UIApplicationDelegate","doc:\/\/com.example.sit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.example.sit\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.example.sit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","type":"conformsTo"}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate\/window"],"generated":true,"anchor":"Instance-Properties"},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate\/application(_:didFinishLaunchingWithOptions:)"]},{"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate\/UIApplicationDelegate-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"metadata":{"symbolKind":"class","navigatorTitle":[{"text":"AppDelegate","kind":"identifier"}],"title":"AppDelegate","role":"symbol","modules":[{"name":"App_SIT"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AppDelegate","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@App_SIT@objc(cs)AppDelegate"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/appdelegate"]},{"paths":["\/documentation\/app_sit\/appdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.example.sit/documentation/App_SIT/AppDelegate/init":{"abstract":[],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate\/init","kind":"symbol","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/app_sit\/appdelegate\/init","title":"init","type":"topic"},"doc://com.example.sit/documentation/App_SIT/AppDelegate/application(_:didFinishLaunchingWithOptions:)":{"title":"application(_:didFinishLaunchingWithOptions:)","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"kind":"text","text":", "},{"text":"didFinishLaunchingWithOptions","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@UIApplicationLaunchOptionsKey","text":"LaunchOptionsKey","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","url":"\/documentation\/app_sit\/appdelegate\/application(_:didfinishlaunchingwithoptions:)","type":"topic","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate\/application(_:didFinishLaunchingWithOptions:)","navigatorTitle":[{"text":"application:didFinishLaunchingWithOptions:","kind":"identifier"}]},"doc://com.example.sit/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/SQ","title":"Swift.Equatable"},"doc://com.example.sit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://com.example.sit/documentation/App_SIT/AppDelegate/UIApplicationDelegate-Implementations":{"abstract":[],"url":"\/documentation\/app_sit\/appdelegate\/uiapplicationdelegate-implementations","role":"collectionGroup","title":"UIApplicationDelegate Implementations","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate\/UIApplicationDelegate-Implementations","type":"topic","kind":"article"},"doc://com.example.sit/SH":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/SH","title":"Swift.Hashable"},"doc://com.example.sit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.example.sit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://com.example.sit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://com.example.sit/objc(pl)UIApplicationDelegate":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIApplicationDelegate","title":"UIApplicationDelegate"},"doc://com.example.sit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.example.sit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.example.sit/documentation/App_SIT/AppDelegate/window":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"window"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIWindow","text":"UIWindow"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate\/window","type":"topic","abstract":[],"title":"window","role":"symbol","url":"\/documentation\/app_sit\/appdelegate\/window","kind":"symbol","navigatorTitle":[{"text":"window","kind":"identifier"}]},"doc://com.example.sit/documentation/App_SIT/AppDelegate":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AppDelegate","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AppDelegate"}],"url":"\/documentation\/app_sit\/appdelegate","kind":"symbol","title":"AppDelegate"},"doc://com.example.sit/objc(cs)UIResponder":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(cs)UIResponder","title":"UIResponder"},"doc://com.example.sit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"AppDelegate"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"text":"AppDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AppDelegate"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate\/window"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate\/application(_:didFinishLaunchingWithOptions:)","doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate\/init"],"generated":true}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.example.sit\/objc(cs)UIResponder"]},{"title":"Conforms To","identifiers":["doc:\/\/com.example.sit\/objc(pl)UIApplicationDelegate"],"kind":"relationships","type":"conformsTo"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AppDelegate"},{"kind":"text","text":" : "},{"text":"UIResponder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIResponder"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate~1application(_:didFinishLaunchingWithOptions:)\/title","value":"application:didFinishLaunchingWithOptions:","op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate~1application(_:didFinishLaunchingWithOptions:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"application:didFinishLaunchingWithOptions:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate~1window\/title","value":"window"},{"op":"replace","value":[{"kind":"identifier","text":"window"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate~1window\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate\/title","value":"AppDelegate"},{"value":[{"text":"AppDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AppDelegate"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate\/navigatorTitle"}]}]}