{"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT"]]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController\/shouldLoad()","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController\/startLoading()","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController\/stopLoading()","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController\/viewDidLoad()"],"title":"Instance Methods","anchor":"Instance-Methods"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseViewController"}],"navigatorTitle":[{"kind":"identifier","text":"BaseViewController"}],"role":"symbol","symbolKind":"class","title":"BaseViewController","externalID":"c:@M@App_SIT@objc(cs)BaseViewController","roleHeading":"Class","modules":[{"name":"App_SIT"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/app_sit\/baseviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/app_sit\/baseviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.example.sit\/objc(cs)UIViewController"]},{"title":"Inherited By","identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController","doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController","doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController"],"kind":"relationships","type":"inheritedBy"},{"identifiers":["doc:\/\/com.example.sit\/objc(pl)NSCoding","doc:\/\/com.example.sit\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.example.sit\/objc(pl)NSObject","doc:\/\/com.example.sit\/s7CVarArgP","doc:\/\/com.example.sit\/s28CustomDebugStringConvertibleP","doc:\/\/com.example.sit\/s23CustomStringConvertibleP","doc:\/\/com.example.sit\/SQ","doc:\/\/com.example.sit\/SH","doc:\/\/com.example.sit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.example.sit\/objc(pl)UIAppearanceContainer","doc:\/\/com.example.sit\/objc(pl)UIContentContainer","doc:\/\/com.example.sit\/objc(pl)UIFocusEnvironment","doc:\/\/com.example.sit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.example.sit\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.example.sit\/objc(pl)UIStateRestoring","doc:\/\/com.example.sit\/5UIKit23UITraitChangeObservableP","doc:\/\/com.example.sit\/objc(pl)UITraitEnvironment","doc:\/\/com.example.sit\/objc(pl)UIUserActivityRestoring","doc:\/\/com.example.sit\/objc(pl)UITraitChangeObservable"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"abstract":[{"type":"text","text":"Base ViewController for manage whole project UIViewController"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseViewController"}],"languages":["swift"]}]},{"content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Easy to handle change that we want to effect whole project","type":"text"}]}]}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController"},"references":{"doc://com.example.sit/documentation/App_SIT/HomeViewController":{"role":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController","navigatorTitle":[{"text":"HomeViewController","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"HomeViewController"},{"text":" class is responsible for managing the home screen of the app.","type":"text"}],"url":"\/documentation\/app_sit\/homeviewcontroller","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HomeViewController","kind":"identifier"}],"title":"HomeViewController","type":"topic"},"doc://com.example.sit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.example.sit\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.example.sit/documentation/App_SIT/LaunchScreenViewController":{"navigatorTitle":[{"kind":"identifier","text":"LaunchScreenViewController"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LaunchScreenViewController"}],"url":"\/documentation\/app_sit\/launchscreenviewcontroller","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController","title":"LaunchScreenViewController","type":"topic","abstract":[],"kind":"symbol"},"doc://com.example.sit/documentation/App_SIT/BaseViewController/viewDidLoad()":{"url":"\/documentation\/app_sit\/baseviewcontroller\/viewdidload()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController\/viewDidLoad()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","title":"viewDidLoad()","abstract":[]},"doc://com.example.sit/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.example.sit\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://com.example.sit/documentation/App_SIT/FeatureOneViewController":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController","type":"topic","navigatorTitle":[{"text":"FeatureOneViewController","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FeatureOneViewController","kind":"identifier"}],"abstract":[],"url":"\/documentation\/app_sit\/featureoneviewcontroller","title":"FeatureOneViewController","role":"symbol"},"doc://com.example.sit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://com.example.sit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.example.sit/documentation/App_SIT/BaseViewController/initWithCoder:":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController\/initWithCoder:","role":"symbol","title":"initWithCoder:","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/app_sit\/baseviewcontroller\/initwithcoder:","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}]},"doc://com.example.sit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.example.sit/objc(pl)UIStateRestoring":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring"},"doc://com.example.sit/documentation/App_SIT/BaseViewController/stopLoading()":{"url":"\/documentation\/app_sit\/baseviewcontroller\/stoploading()","kind":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController\/stopLoading()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"stopLoading","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","title":"stopLoading()","abstract":[{"type":"text","text":"Using StopLoading to stop indicator"}]},"doc://com.example.sit/documentation/App_SIT/BaseViewController/shouldLoad()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"shouldLoad","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController\/shouldLoad()","role":"symbol","title":"shouldLoad()","abstract":[{"text":"Delay 0.5 after ViewDidLoad being called.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/app_sit\/baseviewcontroller\/shouldload()"},"doc://com.example.sit/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://com.example.sit/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/SQ","title":"Swift.Equatable"},"doc://com.example.sit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://com.example.sit/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling"},"doc://com.example.sit/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://com.example.sit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://com.example.sit/objc(pl)UIContentContainer":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer"},"doc://com.example.sit/documentation/App_SIT/BaseViewController/initWithNibName:bundle:":{"kind":"symbol","abstract":[],"title":"initWithNibName:bundle:","url":"\/documentation\/app_sit\/baseviewcontroller\/initwithnibname:bundle:","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController\/initWithNibName:bundle:","type":"topic","role":"symbol","navigatorTitle":[{"text":"initWithNibName:bundle:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"text":"initWithNibName:bundle:","kind":"identifier"}]},"doc://com.example.sit/objc(cs)UIViewController":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(cs)UIViewController","title":"UIViewController"},"doc://com.example.sit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.example.sit/objc(pl)UITraitChangeObservable":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UITraitChangeObservable","title":"UIKit.__UITraitChangeObservable"},"doc://com.example.sit/SH":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/SH","title":"Swift.Hashable"},"doc://com.example.sit/documentation/App_SIT/BaseViewController/startLoading()":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController\/startLoading()","title":"startLoading()","url":"\/documentation\/app_sit\/baseviewcontroller\/startloading()","abstract":[{"text":"Using StartLoading to start indicator","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startLoading"},{"kind":"text","text":"()"}],"type":"topic"},"doc://com.example.sit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://com.example.sit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://com.example.sit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://com.example.sit/documentation/App_SIT/BaseViewController":{"role":"symbol","abstract":[{"type":"text","text":"Base ViewController for manage whole project UIViewController"}],"navigatorTitle":[{"text":"BaseViewController","kind":"identifier"}],"title":"BaseViewController","type":"topic","url":"\/documentation\/app_sit\/baseviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BaseViewController","kind":"identifier"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController","kind":"symbol"},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"BaseViewController","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"BaseViewController","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"BaseViewController","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController\/initWithCoder:","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController\/initWithNibName:bundle:","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController\/viewDidLoad()"],"anchor":"Instance-Methods"}]},{"op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.example.sit\/objc(cs)UIViewController"]},{"type":"inheritedBy","title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController","doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController","doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController"]}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BaseViewController"},{"text":" : ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/title","op":"replace","value":"HomeViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/fragments","value":[{"text":"HomeViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/navigatorTitle","value":[{"text":"HomeViewController","kind":"identifier"}],"op":"replace"},{"value":"LaunchScreenViewController","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController\/fragments","value":[{"text":"LaunchScreenViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController\/navigatorTitle","value":[{"text":"LaunchScreenViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController~1viewDidLoad()\/title","op":"replace","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewDidLoad","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1FeatureOneViewController\/title","op":"replace","value":"FeatureOneViewController"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1FeatureOneViewController\/fragments","value":[{"text":"FeatureOneViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1FeatureOneViewController\/navigatorTitle","value":[{"kind":"identifier","text":"FeatureOneViewController"}]},{"value":"BaseViewController","op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController\/title"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController\/fragments","value":[{"text":"BaseViewController","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"BaseViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}