{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/basetableview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/basetableview"]}],"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView\/contentSize","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView\/intrinsicContentSize"]},{"generated":true,"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView\/reloadData()"],"anchor":"Instance-Methods","title":"Instance Methods"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.example.sit\/objc(cs)UITableView"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.example.sit\/objc(pl)NSCoding","doc:\/\/com.example.sit\/objc(pl)NSObject","doc:\/\/com.example.sit\/objc(pl)CALayerDelegate","doc:\/\/com.example.sit\/7SnapKit25ConstraintRelatableTargetP","doc:\/\/com.example.sit\/7SnapKit20LayoutConstraintItemP","doc:\/\/com.example.sit\/s7CVarArgP","doc:\/\/com.example.sit\/s28CustomDebugStringConvertibleP","doc:\/\/com.example.sit\/s23CustomStringConvertibleP","doc:\/\/com.example.sit\/SQ","doc:\/\/com.example.sit\/SH","doc:\/\/com.example.sit\/s8SendableP","doc:\/\/com.example.sit\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.example.sit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.example.sit\/objc(pl)UIAppearance","doc:\/\/com.example.sit\/objc(pl)UIAppearanceContainer","doc:\/\/com.example.sit\/objc(pl)UICoordinateSpace","doc:\/\/com.example.sit\/objc(pl)UIDataSourceTranslating","doc:\/\/com.example.sit\/objc(pl)UIDynamicItem","doc:\/\/com.example.sit\/objc(pl)UIFocusEnvironment","doc:\/\/com.example.sit\/objc(pl)UIFocusItem","doc:\/\/com.example.sit\/objc(pl)UIFocusItemContainer","doc:\/\/com.example.sit\/objc(pl)UIFocusItemScrollableContainer","doc:\/\/com.example.sit\/objc(pl)UILargeContentViewerItem","doc:\/\/com.example.sit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.example.sit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.example.sit\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.example.sit\/objc(pl)UISpringLoadedInteractionSupporting","doc:\/\/com.example.sit\/5UIKit23UITraitChangeObservableP","doc:\/\/com.example.sit\/objc(pl)UITraitEnvironment","doc:\/\/com.example.sit\/objc(pl)UIUserActivityRestoring","doc:\/\/com.example.sit\/objc(pl)UITraitChangeObservable"]}],"metadata":{"roleHeading":"Class","title":"BaseTableView","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseTableView"}],"symbolKind":"class","role":"symbol","modules":[{"name":"App_SIT"}],"externalID":"c:@M@App_SIT@objc(cs)BaseTableView","navigatorTitle":[{"text":"BaseTableView","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BaseTableView"}]}]}],"references":{"doc://com.example.sit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.example.sit/objc(pl)UIDynamicItem":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem"},"doc://com.example.sit/7SnapKit20LayoutConstraintItemP":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/7SnapKit20LayoutConstraintItemP","title":"SnapKit.LayoutConstraintItem"},"doc://com.example.sit/7SnapKit25ConstraintRelatableTargetP":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/7SnapKit25ConstraintRelatableTargetP","title":"SnapKit.ConstraintRelatableTarget"},"doc://com.example.sit/documentation/App_SIT/BaseTableView/initWithCoder:":{"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/app_sit\/basetableview\/initwithcoder:","abstract":[],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"title":"initWithCoder:","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView\/initWithCoder:"},"doc://com.example.sit/objc(pl)UICoordinateSpace":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace"},"doc://com.example.sit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://com.example.sit/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://com.example.sit/objc(pl)UIAppearance":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIAppearance","title":"UIKit.UIAppearance"},"doc://com.example.sit/objc(pl)UISpringLoadedInteractionSupporting":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UISpringLoadedInteractionSupporting","title":"UIKit.UISpringLoadedInteractionSupporting"},"doc://com.example.sit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://com.example.sit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://com.example.sit/documentation/App_SIT/BaseTableView/contentSize":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"contentSize"}],"url":"\/documentation\/app_sit\/basetableview\/contentsize","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contentSize"},{"text":": ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","title":"contentSize","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView\/contentSize","type":"topic"},"doc://com.example.sit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.example.sit/objc(pl)UIFocusItem":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem"},"doc://com.example.sit/objc(pl)CALayerDelegate":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate"},"doc://com.example.sit/documentation/App_SIT/BaseTableView/initWithFrame:style:":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:style:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:style:"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView\/initWithFrame:style:","role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/app_sit\/basetableview\/initwithframe:style:","title":"initWithFrame:style:"},"doc://com.example.sit/objc(pl)UIDataSourceTranslating":{"title":"UIKit.UIDataSourceTranslating","identifier":"doc:\/\/com.example.sit\/objc(pl)UIDataSourceTranslating","type":"unresolvable"},"doc://com.example.sit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.example.sit\/SH","type":"unresolvable"},"doc://com.example.sit/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.example.sit\/objc(pl)UIFocusEnvironment","type":"unresolvable"},"doc://com.example.sit/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.example.sit\/objc(pl)UIResponderStandardEditActions","type":"unresolvable"},"doc://com.example.sit/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/com.example.sit\/objc(pl)NSCoding","type":"unresolvable"},"doc://com.example.sit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.example.sit\/s7CVarArgP","type":"unresolvable"},"doc://com.example.sit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.example.sit\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.example.sit/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.example.sit\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://com.example.sit/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.example.sit\/objc(pl)UIAccessibilityIdentification","type":"unresolvable"},"doc://com.example.sit/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.example.sit\/objc(pl)UILargeContentViewerItem","type":"unresolvable"},"doc://com.example.sit/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/com.example.sit\/s8SendableP","type":"unresolvable"},"doc://com.example.sit/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.example.sit\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://com.example.sit/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/com.example.sit\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://com.example.sit/objc(pl)UIFocusItemScrollableContainer":{"title":"UIKit.UIFocusItemScrollableContainer","identifier":"doc:\/\/com.example.sit\/objc(pl)UIFocusItemScrollableContainer","type":"unresolvable"},"doc://com.example.sit/objc(cs)UITableView":{"title":"UITableView","identifier":"doc:\/\/com.example.sit\/objc(cs)UITableView","type":"unresolvable"},"doc://com.example.sit/documentation/App_SIT/BaseTableView":{"type":"topic","abstract":[],"url":"\/documentation\/app_sit\/basetableview","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView","navigatorTitle":[{"text":"BaseTableView","kind":"identifier"}],"title":"BaseTableView","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BaseTableView"}]},"doc://com.example.sit/documentation/App_SIT/BaseTableView/intrinsicContentSize":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView\/intrinsicContentSize","type":"topic","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}],"title":"intrinsicContentSize","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"intrinsicContentSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"url":"\/documentation\/app_sit\/basetableview\/intrinsiccontentsize"},"doc://com.example.sit/objc(pl)UITraitChangeObservable":{"title":"UIKit.__UITraitChangeObservable","identifier":"doc:\/\/com.example.sit\/objc(pl)UITraitChangeObservable","type":"unresolvable"},"doc://com.example.sit/documentation/App_SIT/BaseTableView/reloadData()":{"title":"reloadData()","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView\/reloadData()","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reloadData"},{"text":"()","kind":"text"}],"url":"\/documentation\/app_sit\/basetableview\/reloaddata()","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"reloadData","kind":"identifier"}]},"doc://com.example.sit/SQ":{"identifier":"doc:\/\/com.example.sit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIFocusItemContainer","type":"unresolvable","title":"UIKit.UIFocusItemContainer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"BaseTableView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"BaseTableView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"BaseTableView"}]},{"value":[{"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView\/contentSize","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView\/intrinsicContentSize"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView\/initWithCoder:","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView\/initWithFrame:style:","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView\/reloadData()"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.example.sit\/objc(cs)UITableView"],"kind":"relationships","title":"Inherits From"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseTableView"},{"text":" : ","kind":"text"},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"}],"platforms":["iOS"]}]}},{"value":"contentSize","op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView~1contentSize\/title"},{"value":[{"kind":"identifier","text":"contentSize"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView~1contentSize\/fragments"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView\/title","value":"BaseTableView","op":"replace"},{"op":"replace","value":[{"text":"BaseTableView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView\/navigatorTitle","value":[{"text":"BaseTableView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView~1intrinsicContentSize\/title","value":"intrinsicContentSize","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView~1intrinsicContentSize\/fragments","value":[{"kind":"identifier","text":"intrinsicContentSize"}]},{"value":"reloadData","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView~1reloadData()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView~1reloadData()\/fragments","value":[{"kind":"text","text":"- "},{"text":"reloadData","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}