{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/basetableviewcell"]},{"paths":["\/documentation\/app_sit\/basetableviewcell"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT"]]},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.example.sit\/objc(cs)UITableViewCell"]},{"title":"Inherited By","kind":"relationships","type":"inheritedBy","identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell"]},{"type":"conformsTo","identifiers":["doc:\/\/com.example.sit\/objc(pl)NSCoding","doc:\/\/com.example.sit\/objc(pl)NSObject","doc:\/\/com.example.sit\/objc(pl)CALayerDelegate","doc:\/\/com.example.sit\/7SnapKit25ConstraintRelatableTargetP","doc:\/\/com.example.sit\/7SnapKit20LayoutConstraintItemP","doc:\/\/com.example.sit\/s7CVarArgP","doc:\/\/com.example.sit\/s28CustomDebugStringConvertibleP","doc:\/\/com.example.sit\/s23CustomStringConvertibleP","doc:\/\/com.example.sit\/SQ","doc:\/\/com.example.sit\/SH","doc:\/\/com.example.sit\/s8SendableP","doc:\/\/com.example.sit\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.example.sit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.example.sit\/objc(pl)UIAppearance","doc:\/\/com.example.sit\/objc(pl)UIAppearanceContainer","doc:\/\/com.example.sit\/objc(pl)UICoordinateSpace","doc:\/\/com.example.sit\/objc(pl)UIDynamicItem","doc:\/\/com.example.sit\/objc(pl)UIFocusEnvironment","doc:\/\/com.example.sit\/objc(pl)UIFocusItem","doc:\/\/com.example.sit\/objc(pl)UIFocusItemContainer","doc:\/\/com.example.sit\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/com.example.sit\/objc(pl)UILargeContentViewerItem","doc:\/\/com.example.sit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.example.sit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.example.sit\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.example.sit\/5UIKit23UITraitChangeObservableP","doc:\/\/com.example.sit\/objc(pl)UITraitEnvironment","doc:\/\/com.example.sit\/objc(pl)UIUserActivityRestoring","doc:\/\/com.example.sit\/objc(pl)UITraitChangeObservable"],"kind":"relationships","title":"Conforms To"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BaseTableViewCell","kind":"identifier"}],"navigatorTitle":[{"text":"BaseTableViewCell","kind":"identifier"}],"role":"symbol","symbolKind":"class","title":"BaseTableViewCell","externalID":"c:@M@App_SIT@objc(cs)BaseTableViewCell","roleHeading":"Class","modules":[{"name":"App_SIT"}]},"sections":[],"topicSections":[{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell\/awakeFromNib()","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell\/setSelected(_:animated:)"]},{"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell\/identifier","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell\/nib"],"title":"Type Properties","anchor":"Type-Properties","generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BaseTableViewCell","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.example.sit/documentation/App_SIT/BaseTableViewCell/identifier":{"abstract":[],"title":"identifier","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/app_sit\/basetableviewcell\/identifier","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell\/identifier","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"identifier","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.example.sit/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification","type":"unresolvable"},"doc://com.example.sit/7SnapKit20LayoutConstraintItemP":{"identifier":"doc:\/\/com.example.sit\/7SnapKit20LayoutConstraintItemP","title":"SnapKit.LayoutConstraintItem","type":"unresolvable"},"doc://com.example.sit/objc(pl)UIGestureRecognizerDelegate":{"title":"UIKit.UIGestureRecognizerDelegate","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIGestureRecognizerDelegate"},"doc://com.example.sit/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIUserActivityRestoring"},"doc://com.example.sit/documentation/App_SIT/BaseTableViewCell/initWithStyle:reuseIdentifier:":{"title":"initWithStyle:reuseIdentifier:","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell\/initWithStyle:reuseIdentifier:","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"url":"\/documentation\/app_sit\/basetableviewcell\/initwithstyle:reuseidentifier:","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"text":"initWithStyle:reuseIdentifier:","kind":"identifier"}]},"doc://com.example.sit/documentation/App_SIT/BaseTableViewCell":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BaseTableViewCell","kind":"identifier"}],"abstract":[],"url":"\/documentation\/app_sit\/basetableviewcell","type":"topic","navigatorTitle":[{"text":"BaseTableViewCell","kind":"identifier"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell","title":"BaseTableViewCell"},"doc://com.example.sit/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UITraitEnvironment"},"doc://com.example.sit/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/5UIKit23UITraitChangeObservableP"},"doc://com.example.sit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/s23CustomStringConvertibleP"},"doc://com.example.sit/documentation/App_SIT/BaseTableViewCell/initWithCoder:":{"type":"topic","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"title":"initWithCoder:","role":"symbol","abstract":[],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell\/initWithCoder:","kind":"symbol","url":"\/documentation\/app_sit\/basetableviewcell\/initwithcoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},"doc://com.example.sit/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIDynamicItem"},"doc://com.example.sit/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIFocusItemContainer"},"doc://com.example.sit/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIResponderStandardEditActions"},"doc://com.example.sit/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.example.sit/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIFocusEnvironment"},"doc://com.example.sit/documentation/App_SIT/BaseTableViewCell/awakeFromNib()":{"navigatorTitle":[{"text":"awakeFromNib","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"awakeFromNib","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell\/awakeFromNib()","title":"awakeFromNib()","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/app_sit\/basetableviewcell\/awakefromnib()","type":"topic"},"doc://com.example.sit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/s28CustomDebugStringConvertibleP"},"doc://com.example.sit/documentation/App_SIT/BaseTableViewCell/nib":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nib","kind":"identifier"},{"kind":"text","text":": "},{"text":"UINib","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINib"}],"title":"nib","role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/app_sit\/basetableviewcell\/nib","type":"topic","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell\/nib"},"doc://com.example.sit/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UILargeContentViewerItem"},"doc://com.example.sit/objc(cs)UITableViewCell":{"title":"UITableViewCell","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(cs)UITableViewCell"},"doc://com.example.sit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/SQ"},"doc://com.example.sit/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)NSCoding"},"doc://com.example.sit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)NSObject"},"doc://com.example.sit/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/com.example.sit\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate","type":"unresolvable"},"doc://com.example.sit/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://com.example.sit/documentation/App_SIT/BaseTableViewCell/setSelected(_:animated:)":{"url":"\/documentation\/app_sit\/basetableviewcell\/setselected(_:animated:)","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell\/setSelected(_:animated:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setSelected","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"animated"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"abstract":[],"type":"topic","navigatorTitle":[{"text":"setSelected:animated:","kind":"identifier"}],"title":"setSelected(_:animated:)"},"doc://com.example.sit/objc(pl)UICoordinateSpace":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace"},"doc://com.example.sit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://com.example.sit/objc(pl)UIFocusItem":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem","type":"unresolvable"},"doc://com.example.sit/documentation/App_SIT/TestingViewCell":{"navigatorTitle":[{"kind":"identifier","text":"TestingViewCell"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TestingViewCell","kind":"identifier"}],"url":"\/documentation\/app_sit\/testingviewcell","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell","title":"TestingViewCell","type":"topic","abstract":[],"kind":"symbol"},"doc://com.example.sit/s8SendableP":{"identifier":"doc:\/\/com.example.sit\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.example.sit/7SnapKit25ConstraintRelatableTargetP":{"identifier":"doc:\/\/com.example.sit\/7SnapKit25ConstraintRelatableTargetP","title":"SnapKit.ConstraintRelatableTarget","type":"unresolvable"},"doc://com.example.sit/SH":{"identifier":"doc:\/\/com.example.sit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.example.sit/objc(pl)UITraitChangeObservable":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UITraitChangeObservable","title":"UIKit.__UITraitChangeObservable","type":"unresolvable"},"doc://com.example.sit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.example.sit/objc(pl)UIAppearance":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIAppearance","title":"UIKit.UIAppearance"},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"BaseTableViewCell"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"BaseTableViewCell"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"BaseTableViewCell"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell\/awakeFromNib()","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell\/initWithCoder:","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell\/initWithStyle:reuseIdentifier:","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell\/setSelected(_:animated:)"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.example.sit\/objc(cs)UITableViewCell"],"title":"Inherits From"},{"title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell"],"kind":"relationships"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"BaseTableViewCell","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UITableViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableViewCell\/title","value":"BaseTableViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableViewCell\/fragments","value":[{"text":"BaseTableViewCell","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"BaseTableViewCell"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableViewCell\/navigatorTitle"},{"value":"awakeFromNib","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableViewCell~1awakeFromNib()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableViewCell~1awakeFromNib()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"awakeFromNib"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableViewCell~1setSelected(_:animated:)\/title","value":"setSelected:animated:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"setSelected:animated:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableViewCell~1setSelected(_:animated:)\/fragments"},{"value":"TestingViewCell","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell\/fragments","value":[{"text":"TestingViewCell","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell\/navigatorTitle","value":[{"text":"TestingViewCell","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}