{"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeatureOneViewController"}]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController\/viewDidLoad()"],"generated":true,"anchor":"Instance-Methods"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/com.example.sit\/objc(pl)NSCoding","doc:\/\/com.example.sit\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.example.sit\/objc(pl)NSObject","doc:\/\/com.example.sit\/s7CVarArgP","doc:\/\/com.example.sit\/s28CustomDebugStringConvertibleP","doc:\/\/com.example.sit\/s23CustomStringConvertibleP","doc:\/\/com.example.sit\/SQ","doc:\/\/com.example.sit\/SH","doc:\/\/com.example.sit\/s8SendableP","doc:\/\/com.example.sit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.example.sit\/objc(pl)UIAppearanceContainer","doc:\/\/com.example.sit\/objc(pl)UIContentContainer","doc:\/\/com.example.sit\/objc(pl)UIFocusEnvironment","doc:\/\/com.example.sit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.example.sit\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.example.sit\/objc(pl)UIStateRestoring","doc:\/\/com.example.sit\/5UIKit23UITraitChangeObservableP","doc:\/\/com.example.sit\/objc(pl)UITraitEnvironment","doc:\/\/com.example.sit\/objc(pl)UIUserActivityRestoring","doc:\/\/com.example.sit\/objc(pl)UITraitChangeObservable"],"type":"conformsTo","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/featureoneviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/featureoneviewcontroller"]}],"metadata":{"role":"symbol","symbolKind":"class","title":"FeatureOneViewController","navigatorTitle":[{"text":"FeatureOneViewController","kind":"identifier"}],"externalID":"c:@M@App_SIT@objc(cs)FeatureOneViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FeatureOneViewController"}],"roleHeading":"Class","modules":[{"name":"App_SIT"}]},"sections":[],"references":{"doc://com.example.sit/documentation/App_SIT/FeatureOneViewController/initWithCoder:":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController\/initWithCoder:","type":"topic","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"url":"\/documentation\/app_sit\/featureoneviewcontroller\/initwithcoder:","title":"initWithCoder:","role":"symbol"},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.example.sit\/objc(pl)NSObject","type":"unresolvable"},"doc://com.example.sit/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.example.sit\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://com.example.sit/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.example.sit\/objc(pl)UIUserActivityRestoring","type":"unresolvable"},"doc://com.example.sit/objc(pl)NSExtensionRequestHandling":{"title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.example.sit\/objc(pl)NSExtensionRequestHandling","type":"unresolvable"},"doc://com.example.sit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.example.sit\/SQ","type":"unresolvable"},"doc://com.example.sit/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.example.sit\/objc(pl)UIResponderStandardEditActions","type":"unresolvable"},"doc://com.example.sit/documentation/App_SIT/BaseViewController":{"role":"symbol","abstract":[{"type":"text","text":"Base ViewController for manage whole project UIViewController"}],"navigatorTitle":[{"text":"BaseViewController","kind":"identifier"}],"title":"BaseViewController","type":"topic","url":"\/documentation\/app_sit\/baseviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BaseViewController","kind":"identifier"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController","kind":"symbol"},"doc://com.example.sit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.example.sit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.example.sit/documentation/App_SIT/FeatureOneViewController/viewDidLoad()":{"role":"symbol","abstract":[],"navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"title":"viewDidLoad()","type":"topic","url":"\/documentation\/app_sit\/featureoneviewcontroller\/viewdidload()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController\/viewDidLoad()","kind":"symbol"},"doc://com.example.sit/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://com.example.sit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://com.example.sit/documentation/App_SIT/FeatureOneViewController":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController","type":"topic","navigatorTitle":[{"text":"FeatureOneViewController","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FeatureOneViewController","kind":"identifier"}],"abstract":[],"url":"\/documentation\/app_sit\/featureoneviewcontroller","title":"FeatureOneViewController","role":"symbol"},"doc://com.example.sit/SH":{"identifier":"doc:\/\/com.example.sit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.example.sit/documentation/App_SIT/FeatureOneViewController/initWithNibName:bundle:":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController\/initWithNibName:bundle:","type":"topic","navigatorTitle":[{"text":"initWithNibName:bundle:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"url":"\/documentation\/app_sit\/featureoneviewcontroller\/initwithnibname:bundle:","title":"initWithNibName:bundle:","role":"symbol"},"doc://com.example.sit/s8SendableP":{"identifier":"doc:\/\/com.example.sit\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.example.sit/s7CVarArgP":{"identifier":"doc:\/\/com.example.sit\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.example.sit/objc(pl)UIContentContainer":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIContentContainer","type":"unresolvable","title":"UIKit.UIContentContainer"},"doc://com.example.sit/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://com.example.sit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://com.example.sit/objc(pl)UITraitChangeObservable":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UITraitChangeObservable","type":"unresolvable","title":"UIKit.__UITraitChangeObservable"},"doc://com.example.sit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.example.sit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.example.sit/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/com.example.sit\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://com.example.sit/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIStateRestoring","type":"unresolvable","title":"UIKit.UIStateRestoring"},"doc://com.example.sit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"FeatureOneViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FeatureOneViewController"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"FeatureOneViewController","kind":"identifier"}],"op":"replace"},{"value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController\/initWithCoder:","doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController\/initWithNibName:bundle:","doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController\/viewDidLoad()"],"title":"Instance Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController"],"kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FeatureOneViewController"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@App_SIT@objc(cs)BaseViewController","text":"BaseViewController"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"BaseViewController","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController\/title","op":"replace"},{"value":[{"text":"BaseViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController\/fragments"},{"value":[{"text":"BaseViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1FeatureOneViewController~1viewDidLoad()\/title","value":"viewDidLoad","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1FeatureOneViewController~1viewDidLoad()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1FeatureOneViewController\/title","value":"FeatureOneViewController"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1FeatureOneViewController\/fragments","value":[{"kind":"identifier","text":"FeatureOneViewController"}],"op":"replace"},{"value":[{"text":"FeatureOneViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1FeatureOneViewController\/navigatorTitle"}]}]}