{"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController"],"title":"Inherits From"},{"identifiers":["doc:\/\/com.example.sit\/objc(pl)NSCoding","doc:\/\/com.example.sit\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.example.sit\/objc(pl)NSObject","doc:\/\/com.example.sit\/s7CVarArgP","doc:\/\/com.example.sit\/s8CopyableP","doc:\/\/com.example.sit\/s28CustomDebugStringConvertibleP","doc:\/\/com.example.sit\/s23CustomStringConvertibleP","doc:\/\/com.example.sit\/SQ","doc:\/\/com.example.sit\/s9EscapableP","doc:\/\/com.example.sit\/SH","doc:\/\/com.example.sit\/s8SendableP","doc:\/\/com.example.sit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.example.sit\/objc(pl)UIAppearanceContainer","doc:\/\/com.example.sit\/objc(pl)UIContentContainer","doc:\/\/com.example.sit\/objc(pl)UIFocusEnvironment","doc:\/\/com.example.sit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.example.sit\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.example.sit\/objc(pl)UIScrollViewDelegate","doc:\/\/com.example.sit\/objc(pl)UIStateRestoring","doc:\/\/com.example.sit\/objc(pl)UITableViewDataSource","doc:\/\/com.example.sit\/objc(pl)UITableViewDelegate","doc:\/\/com.example.sit\/5UIKit23UITraitChangeObservableP","doc:\/\/com.example.sit\/objc(pl)UITraitEnvironment","doc:\/\/com.example.sit\/objc(pl)UIUserActivityRestoring","doc:\/\/com.example.sit\/objc(pl)UITraitChangeObservable"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/homeviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/homeviewcontroller"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HomeViewController"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Overview","level":2,"anchor":"overview","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This class provides the main interface for users to interact with the home screen."},{"type":"text","text":" "},{"type":"text","text":"It includes features like navigation and data display."}]}]}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"HomeViewController"},{"type":"text","text":" class is responsible for managing the home screen of the app."}],"topicSections":[{"anchor":"Topics","identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/viewDidLoad()"]},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/homeRouter","doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/tableView"],"anchor":"Instance-Properties"},{"generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/UITableViewDataSource-Implementations","doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/UITableViewDelegate-Implementations"],"title":"Default Implementations"}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController"],"anchor":"Related-Documentation","title":"Related Documentation"}],"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT"]]},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HomeViewController","kind":"identifier"}],"symbolKind":"class","externalID":"c:@M@App_SIT@objc(cs)HomeViewController","roleHeading":"Class","modules":[{"name":"App_SIT"}],"role":"symbol","navigatorTitle":[{"text":"HomeViewController","kind":"identifier"}],"title":"HomeViewController"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.example.sit/SH":{"identifier":"doc:\/\/com.example.sit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.example.sit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://com.example.sit/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://com.example.sit/SQ":{"identifier":"doc:\/\/com.example.sit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.example.sit/objc(pl)UITableViewDataSource":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UITableViewDataSource","title":"UITableViewDataSource","type":"unresolvable"},"doc://com.example.sit/documentation/App_SIT/HomeViewController/homeRouter":{"url":"\/documentation\/app_sit\/homeviewcontroller\/homerouter","type":"topic","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/homeRouter","role":"symbol","abstract":[],"kind":"symbol","title":"homeRouter","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"homeRouter","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HomeViewRouter","preciseIdentifier":"s:7App_SIT14HomeViewRouterC"}]},"doc://com.example.sit/objc(pl)UITraitChangeObservable":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UITraitChangeObservable","title":"UIKit.__UITraitChangeObservable","type":"unresolvable"},"doc://com.example.sit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.example.sit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.example.sit/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://com.example.sit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.example.sit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.example.sit/objc(pl)NSObject":{"identifier":"doc:\/\/com.example.sit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.example.sit/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://com.example.sit/documentation/App_SIT/HomeViewController/initWithNibName:bundle:":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/initWithNibName:bundle:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithNibName:bundle:","kind":"identifier"}],"url":"\/documentation\/app_sit\/homeviewcontroller\/initwithnibname:bundle:","title":"initWithNibName:bundle:","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}]},"doc://com.example.sit/objc(pl)UIContentContainer":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer","type":"unresolvable"},"doc://com.example.sit/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://com.example.sit/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/com.example.sit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://com.example.sit/s9EscapableP":{"identifier":"doc:\/\/com.example.sit\/s9EscapableP","title":"Swift.Escapable","type":"unresolvable"},"doc://com.example.sit/documentation/App_SIT/HomeViewController/initWithCoder:":{"abstract":[],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/app_sit\/homeviewcontroller\/initwithcoder:","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/initWithCoder:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"title":"initWithCoder:"},"doc://com.example.sit/objc(pl)UIScrollViewDelegate":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIScrollViewDelegate","title":"UIKit.UIScrollViewDelegate","type":"unresolvable"},"doc://com.example.sit/documentation/App_SIT/BaseViewController":{"role":"symbol","abstract":[{"type":"text","text":"Base ViewController for manage whole project UIViewController"}],"navigatorTitle":[{"text":"BaseViewController","kind":"identifier"}],"title":"BaseViewController","type":"topic","url":"\/documentation\/app_sit\/baseviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BaseViewController","kind":"identifier"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController","kind":"symbol"},"doc://com.example.sit/s8CopyableP":{"identifier":"doc:\/\/com.example.sit\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"},"doc://com.example.sit/documentation/App_SIT/HomeViewController/UITableViewDataSource-Implementations":{"title":"UITableViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/UITableViewDataSource-Implementations","url":"\/documentation\/app_sit\/homeviewcontroller\/uitableviewdatasource-implementations","role":"collectionGroup","kind":"article","type":"topic"},"doc://com.example.sit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://com.example.sit/s7CVarArgP":{"identifier":"doc:\/\/com.example.sit\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.example.sit/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring","type":"unresolvable"},"doc://com.example.sit/objc(pl)NSCoding":{"identifier":"doc:\/\/com.example.sit\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://com.example.sit/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://com.example.sit/documentation/App_SIT/HomeViewController":{"role":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController","navigatorTitle":[{"text":"HomeViewController","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"HomeViewController"},{"text":" class is responsible for managing the home screen of the app.","type":"text"}],"url":"\/documentation\/app_sit\/homeviewcontroller","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HomeViewController","kind":"identifier"}],"title":"HomeViewController","type":"topic"},"doc://com.example.sit/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/com.example.sit\/s8SendableP","type":"unresolvable"},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/objc(pl)NSExtensionRequestHandling":{"title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.example.sit\/objc(pl)NSExtensionRequestHandling","type":"unresolvable"},"doc://com.example.sit/documentation/App_SIT/HomeViewController/UITableViewDelegate-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/UITableViewDelegate-Implementations","abstract":[],"url":"\/documentation\/app_sit\/homeviewcontroller\/uitableviewdelegate-implementations","kind":"article","title":"UITableViewDelegate Implementations","type":"topic"},"doc://com.example.sit/documentation/App_SIT/FeatureOneViewController":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController","type":"topic","navigatorTitle":[{"text":"FeatureOneViewController","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FeatureOneViewController","kind":"identifier"}],"abstract":[],"url":"\/documentation\/app_sit\/featureoneviewcontroller","title":"FeatureOneViewController","role":"symbol"},"doc://com.example.sit/documentation/App_SIT/HomeViewController/tableView":{"title":"tableView","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/tableView","abstract":[],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@App_SIT@objc(cs)BaseTableView","text":"BaseTableView"},{"text":"!","kind":"text"}],"url":"\/documentation\/app_sit\/homeviewcontroller\/tableview","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"tableView"}]},"doc://com.example.sit/documentation/App_SIT/HomeViewController/viewDidLoad()":{"title":"viewDidLoad()","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/viewDidLoad()","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"url":"\/documentation\/app_sit\/homeviewcontroller\/viewdidload()","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}]},"doc://com.example.sit/objc(pl)UITableViewDelegate":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UITableViewDelegate","title":"UITableViewDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"HomeViewController"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"HomeViewController","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"HomeViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Topics","identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/viewDidLoad()"]},{"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/tableView"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"generated":true,"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/initWithCoder:","doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/initWithNibName:bundle:"],"anchor":"Instance-Methods","title":"Instance Methods"},{"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/UITableViewDataSource-Implementations","doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController\/UITableViewDelegate-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations","generated":true}]},{"value":[{"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/com.example.sit\/objc(pl)UITableViewDataSource","doc:\/\/com.example.sit\/objc(pl)UITableViewDelegate"],"title":"Conforms To","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController"],"title":"Related Documentation","anchor":"Related-Documentation"}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HomeViewController"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@App_SIT@objc(cs)BaseViewController","text":"BaseViewController"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController\/title","op":"replace","value":"BaseViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController\/fragments","value":[{"text":"BaseViewController","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"BaseViewController"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/title","op":"replace","value":"HomeViewController"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/fragments","value":[{"text":"HomeViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/navigatorTitle","value":[{"text":"HomeViewController","kind":"identifier"}]},{"op":"replace","value":"FeatureOneViewController","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1FeatureOneViewController\/title"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1FeatureOneViewController\/fragments","value":[{"text":"FeatureOneViewController","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"FeatureOneViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1FeatureOneViewController\/navigatorTitle"},{"value":"tableView","op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController~1tableView\/title"},{"value":[{"kind":"identifier","text":"tableView"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController~1tableView\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController~1viewDidLoad()\/title","op":"replace","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController~1viewDidLoad()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}]}]}]}