{"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController\/laucher"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController\/viewDidLoad()"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"metadata":{"roleHeading":"Class","title":"LaunchScreenViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LaunchScreenViewController"}],"symbolKind":"class","role":"symbol","modules":[{"name":"App_SIT"}],"externalID":"c:@M@App_SIT@objc(cs)LaunchScreenViewController","navigatorTitle":[{"text":"LaunchScreenViewController","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/launchscreenviewcontroller"]},{"paths":["\/documentation\/app_sit\/launchscreenviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LaunchScreenViewController","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.example.sit\/objc(pl)NSCoding","doc:\/\/com.example.sit\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.example.sit\/objc(pl)NSObject","doc:\/\/com.example.sit\/s7CVarArgP","doc:\/\/com.example.sit\/s28CustomDebugStringConvertibleP","doc:\/\/com.example.sit\/s23CustomStringConvertibleP","doc:\/\/com.example.sit\/SQ","doc:\/\/com.example.sit\/SH","doc:\/\/com.example.sit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.example.sit\/objc(pl)UIAppearanceContainer","doc:\/\/com.example.sit\/objc(pl)UIContentContainer","doc:\/\/com.example.sit\/objc(pl)UIFocusEnvironment","doc:\/\/com.example.sit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.example.sit\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.example.sit\/objc(pl)UIStateRestoring","doc:\/\/com.example.sit\/5UIKit23UITraitChangeObservableP","doc:\/\/com.example.sit\/objc(pl)UITraitEnvironment","doc:\/\/com.example.sit\/objc(pl)UIUserActivityRestoring","doc:\/\/com.example.sit\/objc(pl)UITraitChangeObservable"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController"},"sections":[],"kind":"symbol","references":{"doc://com.example.sit/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring","type":"unresolvable"},"doc://com.example.sit/objc(pl)NSObject":{"identifier":"doc:\/\/com.example.sit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.example.sit/documentation/App_SIT/LaunchScreenViewController":{"navigatorTitle":[{"kind":"identifier","text":"LaunchScreenViewController"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LaunchScreenViewController"}],"url":"\/documentation\/app_sit\/launchscreenviewcontroller","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController","title":"LaunchScreenViewController","type":"topic","abstract":[],"kind":"symbol"},"doc://com.example.sit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://com.example.sit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://com.example.sit/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://com.example.sit/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://com.example.sit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.example.sit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.example.sit/documentation/App_SIT/LaunchScreenViewController/initWithNibName:bundle:":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController\/initWithNibName:bundle:","abstract":[],"url":"\/documentation\/app_sit\/launchscreenviewcontroller\/initwithnibname:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"type":"topic","kind":"symbol","title":"initWithNibName:bundle:","role":"symbol","navigatorTitle":[{"text":"initWithNibName:bundle:","kind":"identifier"}]},"doc://com.example.sit/objc(pl)UIContentContainer":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer","type":"unresolvable"},"doc://com.example.sit/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://com.example.sit/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://com.example.sit/documentation/App_SIT/LaunchScreenViewController/initWithCoder:":{"type":"topic","title":"initWithCoder:","kind":"symbol","url":"\/documentation\/app_sit\/launchscreenviewcontroller\/initwithcoder:","abstract":[],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController\/initWithCoder:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}]},"doc://com.example.sit/SH":{"identifier":"doc:\/\/com.example.sit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.example.sit/objc(pl)NSCoding":{"identifier":"doc:\/\/com.example.sit\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://com.example.sit/s7CVarArgP":{"identifier":"doc:\/\/com.example.sit\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.example.sit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.example.sit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.example.sit/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://com.example.sit/documentation/App_SIT/LaunchScreenViewController/laucher":{"url":"\/documentation\/app_sit\/launchscreenviewcontroller\/laucher","type":"topic","abstract":[],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController\/laucher","role":"symbol","kind":"symbol","title":"laucher","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"laucher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7App_SIT18LaunchScreenRouterC","text":"LaunchScreenRouter"}]},"doc://com.example.sit/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/com.example.sit\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling","type":"unresolvable"},"doc://com.example.sit/documentation/App_SIT/LaunchScreenViewController/viewDidLoad()":{"url":"\/documentation\/app_sit\/launchscreenviewcontroller\/viewdidload()","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController\/viewDidLoad()","title":"viewDidLoad()","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidLoad","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic"},"doc://com.example.sit/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/com.example.sit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://com.example.sit/documentation/App_SIT/BaseViewController":{"role":"symbol","abstract":[{"type":"text","text":"Base ViewController for manage whole project UIViewController"}],"navigatorTitle":[{"text":"BaseViewController","kind":"identifier"}],"title":"BaseViewController","type":"topic","url":"\/documentation\/app_sit\/baseviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BaseViewController","kind":"identifier"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController","kind":"symbol"},"doc://com.example.sit/objc(pl)UITraitChangeObservable":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UITraitChangeObservable","title":"UIKit.__UITraitChangeObservable","type":"unresolvable"},"doc://com.example.sit/SQ":{"identifier":"doc:\/\/com.example.sit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"LaunchScreenViewController","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LaunchScreenViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"LaunchScreenViewController","kind":"identifier"}]},{"value":[{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController\/initWithCoder:","doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController\/initWithNibName:bundle:","doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController\/viewDidLoad()"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LaunchScreenViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController","preciseIdentifier":"c:@M@App_SIT@objc(cs)BaseViewController","text":"BaseViewController"}]}]},"path":"\/primaryContentSections\/0"},{"value":"LaunchScreenViewController","op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController\/fragments","value":[{"text":"LaunchScreenViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController\/navigatorTitle","value":[{"text":"LaunchScreenViewController","kind":"identifier"}]},{"value":"viewDidLoad","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController~1viewDidLoad()\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"viewDidLoad","kind":"identifier"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController~1viewDidLoad()\/fragments"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController\/title","op":"replace","value":"BaseViewController"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController\/fragments","value":[{"text":"BaseViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"BaseViewController"}]}]}]}