{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LoadingViewController"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/app_sit\/loadingviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/app_sit\/loadingviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"title":"LoadingViewController","symbolKind":"class","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LoadingViewController"}],"navigatorTitle":[{"text":"LoadingViewController","kind":"identifier"}],"externalID":"c:@M@App_SIT@objc(cs)LoadingViewController","role":"symbol","modules":[{"name":"App_SIT"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT"]]},"topicSections":[{"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController\/startLoading()","doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController\/stopLoading()","doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController\/viewDidLoad()"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.example.sit\/objc(cs)UIViewController"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/com.example.sit\/objc(pl)NSCoding","doc:\/\/com.example.sit\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.example.sit\/objc(pl)NSObject","doc:\/\/com.example.sit\/s7CVarArgP","doc:\/\/com.example.sit\/s28CustomDebugStringConvertibleP","doc:\/\/com.example.sit\/s23CustomStringConvertibleP","doc:\/\/com.example.sit\/SQ","doc:\/\/com.example.sit\/SH","doc:\/\/com.example.sit\/s8SendableP","doc:\/\/com.example.sit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.example.sit\/objc(pl)UIAppearanceContainer","doc:\/\/com.example.sit\/objc(pl)UIContentContainer","doc:\/\/com.example.sit\/objc(pl)UIFocusEnvironment","doc:\/\/com.example.sit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.example.sit\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.example.sit\/objc(pl)UIStateRestoring","doc:\/\/com.example.sit\/5UIKit23UITraitChangeObservableP","doc:\/\/com.example.sit\/objc(pl)UITraitEnvironment","doc:\/\/com.example.sit\/objc(pl)UIUserActivityRestoring","doc:\/\/com.example.sit\/objc(pl)UITraitChangeObservable"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.example.sit/documentation/App_SIT/LoadingViewController/initWithNibName:bundle:":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"role":"symbol","title":"initWithNibName:bundle:","url":"\/documentation\/app_sit\/loadingviewcontroller\/initwithnibname:bundle:","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController\/initWithNibName:bundle:","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithNibName:bundle:","kind":"identifier"}]},"doc://com.example.sit/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/s7CVarArgP"},"doc://com.example.sit/documentation/App_SIT/LoadingViewController/stopLoading()":{"abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"stopLoading","kind":"identifier"},{"kind":"text","text":"()"}],"title":"stopLoading()","role":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController\/stopLoading()","url":"\/documentation\/app_sit\/loadingviewcontroller\/stoploading()"},"doc://com.example.sit/documentation/App_SIT/LoadingViewController/startLoading()":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController\/startLoading()","kind":"symbol","title":"startLoading()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startLoading"},{"text":"()","kind":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/app_sit\/loadingviewcontroller\/startloading()","abstract":[]},"doc://com.example.sit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.example.sit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.example.sit/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/5UIKit23UITraitChangeObservableP"},"doc://com.example.sit/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIFocusEnvironment"},"doc://com.example.sit/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIAppearanceContainer"},"doc://com.example.sit/objc(pl)NSExtensionRequestHandling":{"title":"Foundation.NSExtensionRequestHandling","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)NSExtensionRequestHandling"},"doc://com.example.sit/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/s8SendableP"},"doc://com.example.sit/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.example.sit/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.example.sit/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIUserActivityRestoring"},"doc://com.example.sit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/s23CustomStringConvertibleP"},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)NSObject"},"doc://com.example.sit/SQ":{"identifier":"doc:\/\/com.example.sit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.example.sit/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://com.example.sit/documentation/App_SIT/LoadingViewController/viewDidLoad()":{"abstract":[],"role":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController\/viewDidLoad()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/app_sit\/loadingviewcontroller\/viewdidload()","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"type":"topic"},"doc://com.example.sit/objc(pl)UITraitChangeObservable":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UITraitChangeObservable","title":"UIKit.__UITraitChangeObservable","type":"unresolvable"},"doc://com.example.sit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://com.example.sit/SH":{"identifier":"doc:\/\/com.example.sit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.example.sit/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring","type":"unresolvable"},"doc://com.example.sit/documentation/App_SIT/LoadingViewController":{"url":"\/documentation\/app_sit\/loadingviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoadingViewController"}],"type":"topic","navigatorTitle":[{"text":"LoadingViewController","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController","role":"symbol","kind":"symbol","title":"LoadingViewController"},"doc://com.example.sit/objc(pl)UIContentContainer":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer","type":"unresolvable"},"doc://com.example.sit/objc(cs)UIViewController":{"identifier":"doc:\/\/com.example.sit\/objc(cs)UIViewController","title":"UIViewController","type":"unresolvable"},"doc://com.example.sit/documentation/App_SIT/LoadingViewController/initWithCoder:":{"title":"initWithCoder:","url":"\/documentation\/app_sit\/loadingviewcontroller\/initwithcoder:","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController\/initWithCoder:"},"doc://com.example.sit/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)NSCoding"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"LoadingViewController","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"LoadingViewController","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"LoadingViewController"}]},{"value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController\/initWithCoder:","doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController\/initWithNibName:bundle:","doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController\/viewDidLoad()"],"anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.example.sit\/objc(cs)UIViewController"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoadingViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"viewDidLoad","op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LoadingViewController~1viewDidLoad()\/title"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LoadingViewController~1viewDidLoad()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LoadingViewController\/title","value":"LoadingViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LoadingViewController\/fragments","value":[{"text":"LoadingViewController","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"LoadingViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LoadingViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}