{"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.example.sit\/objc(cs)UIResponder"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.example.sit\/objc(pl)NSObject","doc:\/\/com.example.sit\/s7CVarArgP","doc:\/\/com.example.sit\/s28CustomDebugStringConvertibleP","doc:\/\/com.example.sit\/s23CustomStringConvertibleP","doc:\/\/com.example.sit\/SQ","doc:\/\/com.example.sit\/SH","doc:\/\/com.example.sit\/s8SendableP","doc:\/\/com.example.sit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.example.sit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.example.sit\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.example.sit\/objc(pl)UISceneDelegate","doc:\/\/com.example.sit\/objc(pl)UIUserActivityRestoring","doc:\/\/com.example.sit\/objc(pl)UIWindowSceneDelegate"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/scenedelegate"]},{"paths":["\/documentation\/app_sit\/scenedelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"roleHeading":"Class","title":"SceneDelegate","modules":[{"name":"App_SIT"}],"platforms":[{"deprecated":false,"unavailable":false,"name":"iOS","beta":false,"introducedAt":"13.0"},{"deprecated":false,"name":"iPadOS","introducedAt":"13.0","beta":false,"unavailable":false},{"name":"Mac Catalyst","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"13.0"}],"symbolKind":"class","navigatorTitle":[{"text":"SceneDelegate","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SceneDelegate"}],"role":"symbol","externalID":"c:@M@App_SIT@objc(cs)SceneDelegate"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SceneDelegate"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/window"]},{"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/scene(_:willConnectTo:options:)","doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/sceneDidBecomeActive(_:)","doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/sceneDidDisconnect(_:)","doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/sceneDidEnterBackground(_:)","doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/sceneWillEnterForeground(_:)","doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/sceneWillResignActive(_:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate"},"references":{"doc://com.example.sit/documentation/App_SIT/SceneDelegate/init":{"abstract":[],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/init","title":"init","url":"\/documentation\/app_sit\/scenedelegate\/init","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"doc://com.example.sit/documentation/App_SIT/SceneDelegate/scene(_:willConnectTo:options:)":{"abstract":[],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/scene(_:willConnectTo:options:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scene","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIScene","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScene"},{"text":", ","kind":"text"},{"text":"willConnectTo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UISceneSession","kind":"typeIdentifier","text":"UISceneSession"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIScene","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":"."},{"preciseIdentifier":"c:objc(cs)UISceneConnectionOptions","text":"ConnectionOptions","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"scene:willConnectToSession:options:"}],"title":"scene(_:willConnectTo:options:)","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/app_sit\/scenedelegate\/scene(_:willconnectto:options:)"},"doc://com.example.sit/objc(cs)UIResponder":{"identifier":"doc:\/\/com.example.sit\/objc(cs)UIResponder","type":"unresolvable","title":"UIResponder"},"doc://com.example.sit/documentation/App_SIT/SceneDelegate/sceneWillEnterForeground(_:)":{"abstract":[],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/sceneWillEnterForeground(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sceneWillEnterForeground","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIScene","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"sceneWillEnterForeground:","kind":"identifier"}],"title":"sceneWillEnterForeground(_:)","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/app_sit\/scenedelegate\/scenewillenterforeground(_:)"},"doc://com.example.sit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://com.example.sit/objc(pl)UISceneDelegate":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UISceneDelegate","title":"UIKit.UISceneDelegate"},"doc://com.example.sit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/SH":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/SH","title":"Swift.Hashable"},"doc://com.example.sit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.example.sit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://com.example.sit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.example.sit/documentation/App_SIT/SceneDelegate/sceneDidBecomeActive(_:)":{"title":"sceneDidBecomeActive(_:)","kind":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/sceneDidBecomeActive(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sceneDidBecomeActive","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIScene","text":"UIScene","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/app_sit\/scenedelegate\/scenedidbecomeactive(_:)","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sceneDidBecomeActive:"}]},"doc://com.example.sit/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://com.example.sit/objc(pl)UIWindowSceneDelegate":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIWindowSceneDelegate","type":"unresolvable","title":"UIWindowSceneDelegate"},"doc://com.example.sit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://com.example.sit/documentation/App_SIT/SceneDelegate/sceneWillResignActive(_:)":{"title":"sceneWillResignActive(_:)","kind":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/sceneWillResignActive(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sceneWillResignActive","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIScene","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":")"}],"url":"\/documentation\/app_sit\/scenedelegate\/scenewillresignactive(_:)","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"text":"sceneWillResignActive:","kind":"identifier"}]},"doc://com.example.sit/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/s8SendableP","title":"Swift.Sendable"},"doc://com.example.sit/documentation/App_SIT/SceneDelegate/window":{"title":"window","kind":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/window","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"window","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIWindow","text":"UIWindow","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/app_sit\/scenedelegate\/window","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"window"}]},"doc://com.example.sit/documentation/App_SIT/SceneDelegate/sceneDidEnterBackground(_:)":{"kind":"symbol","url":"\/documentation\/app_sit\/scenedelegate\/scenedidenterbackground(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sceneDidEnterBackground","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIScene","preciseIdentifier":"c:objc(cs)UIScene"},{"text":")","kind":"text"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"sceneDidEnterBackground:"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/sceneDidEnterBackground(_:)","type":"topic","title":"sceneDidEnterBackground(_:)"},"doc://com.example.sit/documentation/App_SIT/SceneDelegate":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate","url":"\/documentation\/app_sit\/scenedelegate","kind":"symbol","title":"SceneDelegate","role":"symbol","navigatorTitle":[{"text":"SceneDelegate","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SceneDelegate","kind":"identifier"}]},"doc://com.example.sit/SQ":{"identifier":"doc:\/\/com.example.sit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.example.sit/documentation/App_SIT/SceneDelegate/sceneDidDisconnect(_:)":{"title":"sceneDidDisconnect(_:)","kind":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/sceneDidDisconnect(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sceneDidDisconnect","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIScene","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":")"}],"url":"\/documentation\/app_sit\/scenedelegate\/scenediddisconnect(_:)","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"text":"sceneDidDisconnect:","kind":"identifier"}]},"doc://com.example.sit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":[{"introducedAt":"13.0","deprecated":false,"beta":false,"name":"iOS","unavailable":false},{"name":"iPadOS","introducedAt":"13.0","deprecated":false,"unavailable":false,"beta":false},{"beta":false,"unavailable":false,"introducedAt":"13.0","deprecated":false,"name":"Mac Catalyst"}],"op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"SceneDelegate","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"SceneDelegate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SceneDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/window"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/init","doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/scene(_:willConnectTo:options:)","doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/sceneDidBecomeActive(_:)","doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/sceneDidDisconnect(_:)","doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/sceneDidEnterBackground(_:)","doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/sceneWillEnterForeground(_:)","doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate\/sceneWillResignActive(_:)"],"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.example.sit\/objc(cs)UIResponder"]},{"identifiers":["doc:\/\/com.example.sit\/objc(pl)UIWindowSceneDelegate"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SceneDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UIResponder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIResponder"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"scene:willConnectToSession:options:","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate~1scene(_:willConnectTo:options:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate~1scene(_:willConnectTo:options:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"scene:willConnectToSession:options:","kind":"identifier"}]},{"value":"sceneWillEnterForeground:","op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate~1sceneWillEnterForeground(_:)\/title"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate~1sceneWillEnterForeground(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"sceneWillEnterForeground:","kind":"identifier"}],"op":"replace"},{"value":"sceneDidBecomeActive:","op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate~1sceneDidBecomeActive(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate~1sceneDidBecomeActive(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sceneDidBecomeActive:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate~1sceneWillResignActive(_:)\/title","value":"sceneWillResignActive:"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate~1sceneWillResignActive(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"sceneWillResignActive:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate~1window\/title","value":"window"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate~1window\/fragments","value":[{"kind":"identifier","text":"window"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate~1sceneDidEnterBackground(_:)\/title","value":"sceneDidEnterBackground:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"sceneDidEnterBackground:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate~1sceneDidEnterBackground(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate\/title","op":"replace","value":"SceneDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate\/fragments","value":[{"text":"SceneDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SceneDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate~1sceneDidDisconnect(_:)\/title","value":"sceneDidDisconnect:"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate~1sceneDidDisconnect(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sceneDidDisconnect:"}],"op":"replace"}]}]}