{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/testingviewcell"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/testingviewcell"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell\/nameLabel"],"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell\/awakeFromNib()","doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell\/config(name:)","doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell\/setSelected(_:animated:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TestingViewCell","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TestingViewCell"}],"externalID":"c:@M@App_SIT@objc(cs)TestingViewCell","roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"text":"TestingViewCell","kind":"identifier"}],"role":"symbol","modules":[{"name":"App_SIT"}],"title":"TestingViewCell"},"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT"]]},"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.example.sit\/objc(pl)NSCoding","doc:\/\/com.example.sit\/objc(pl)NSObject","doc:\/\/com.example.sit\/objc(pl)CALayerDelegate","doc:\/\/com.example.sit\/7SnapKit25ConstraintRelatableTargetP","doc:\/\/com.example.sit\/7SnapKit20LayoutConstraintItemP","doc:\/\/com.example.sit\/s7CVarArgP","doc:\/\/com.example.sit\/s28CustomDebugStringConvertibleP","doc:\/\/com.example.sit\/s23CustomStringConvertibleP","doc:\/\/com.example.sit\/SQ","doc:\/\/com.example.sit\/SH","doc:\/\/com.example.sit\/s8SendableP","doc:\/\/com.example.sit\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.example.sit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.example.sit\/objc(pl)UIAppearance","doc:\/\/com.example.sit\/objc(pl)UIAppearanceContainer","doc:\/\/com.example.sit\/objc(pl)UICoordinateSpace","doc:\/\/com.example.sit\/objc(pl)UIDynamicItem","doc:\/\/com.example.sit\/objc(pl)UIFocusEnvironment","doc:\/\/com.example.sit\/objc(pl)UIFocusItem","doc:\/\/com.example.sit\/objc(pl)UIFocusItemContainer","doc:\/\/com.example.sit\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/com.example.sit\/objc(pl)UILargeContentViewerItem","doc:\/\/com.example.sit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.example.sit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.example.sit\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.example.sit\/5UIKit23UITraitChangeObservableP","doc:\/\/com.example.sit\/objc(pl)UITraitEnvironment","doc:\/\/com.example.sit\/objc(pl)UIUserActivityRestoring","doc:\/\/com.example.sit\/objc(pl)UITraitChangeObservable"],"type":"conformsTo"}],"references":{"doc://com.example.sit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.example.sit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.example.sit/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIAccessibilityIdentification","type":"unresolvable","title":"UIKit.UIAccessibilityIdentification"},"doc://com.example.sit/objc(pl)UITraitChangeObservable":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UITraitChangeObservable","type":"unresolvable","title":"UIKit.__UITraitChangeObservable"},"doc://com.example.sit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://com.example.sit/objc(pl)UIFocusItem":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIFocusItem","type":"unresolvable","title":"UIKit.UIFocusItem"},"doc://com.example.sit/documentation/App_SIT/TestingViewCell/initWithStyle:reuseIdentifier:":{"title":"initWithStyle:reuseIdentifier:","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithStyle:reuseIdentifier:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell\/initWithStyle:reuseIdentifier:","kind":"symbol","navigatorTitle":[{"text":"initWithStyle:reuseIdentifier:","kind":"identifier"}],"type":"topic","url":"\/documentation\/app_sit\/testingviewcell\/initwithstyle:reuseidentifier:"},"doc://com.example.sit/objc(pl)NSCoding":{"identifier":"doc:\/\/com.example.sit\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://com.example.sit/documentation/App_SIT/TestingViewCell/setSelected(_:animated:)":{"type":"topic","url":"\/documentation\/app_sit\/testingviewcell\/setselected(_:animated:)","title":"setSelected(_:animated:)","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"setSelected:animated:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setSelected"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell\/setSelected(_:animated:)"},"doc://com.example.sit/documentation/App_SIT/TestingViewCell/nameLabel":{"kind":"symbol","abstract":[],"url":"\/documentation\/app_sit\/testingviewcell\/namelabel","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell\/nameLabel","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nameLabel"},{"text":": ","kind":"text"},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"},{"text":"!","kind":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"nameLabel","kind":"identifier"}],"title":"nameLabel"},"doc://com.example.sit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://com.example.sit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.example.sit\/s28CustomDebugStringConvertibleP"},"doc://com.example.sit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.example.sit\/s8SendableP"},"doc://com.example.sit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.example.sit\/s7CVarArgP"},"doc://com.example.sit/documentation/App_SIT/TestingViewCell/awakeFromNib()":{"kind":"symbol","abstract":[],"title":"awakeFromNib()","type":"topic","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell\/awakeFromNib()","url":"\/documentation\/app_sit\/testingviewcell\/awakefromnib()","role":"symbol","navigatorTitle":[{"text":"awakeFromNib","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"awakeFromNib"},{"kind":"text","text":"()"}]},"doc://com.example.sit/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://com.example.sit/documentation/App_SIT/TestingViewCell/initWithCoder:":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell\/initWithCoder:","type":"topic","role":"symbol","title":"initWithCoder:","url":"\/documentation\/app_sit\/testingviewcell\/initwithcoder:","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"kind":"symbol","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}]},"doc://com.example.sit/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIFocusItemContainer","type":"unresolvable","title":"UIKit.UIFocusItemContainer"},"doc://com.example.sit/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UILargeContentViewerItem","type":"unresolvable","title":"UIKit.UILargeContentViewerItem"},"doc://com.example.sit/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://com.example.sit/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://com.example.sit/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UICoordinateSpace","type":"unresolvable","title":"UIKit.UICoordinateSpace"},"doc://com.example.sit/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/com.example.sit\/objc(pl)CALayerDelegate","type":"unresolvable","title":"QuartzCore.CALayerDelegate"},"doc://com.example.sit/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/com.example.sit\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://com.example.sit/objc(pl)NSObject":{"identifier":"doc:\/\/com.example.sit\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://com.example.sit/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/SQ","title":"Swift.Equatable"},"doc://com.example.sit/objc(pl)UIGestureRecognizerDelegate":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIGestureRecognizerDelegate","title":"UIKit.UIGestureRecognizerDelegate"},"doc://com.example.sit/objc(pl)UIDynamicItem":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem"},"doc://com.example.sit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://com.example.sit/7SnapKit25ConstraintRelatableTargetP":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/7SnapKit25ConstraintRelatableTargetP","title":"SnapKit.ConstraintRelatableTarget"},"doc://com.example.sit/documentation/App_SIT/TestingViewCell":{"navigatorTitle":[{"kind":"identifier","text":"TestingViewCell"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TestingViewCell","kind":"identifier"}],"url":"\/documentation\/app_sit\/testingviewcell","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell","title":"TestingViewCell","type":"topic","abstract":[],"kind":"symbol"},"doc://com.example.sit/objc(pl)UIAppearance":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/objc(pl)UIAppearance","title":"UIKit.UIAppearance"},"doc://com.example.sit/7SnapKit20LayoutConstraintItemP":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/7SnapKit20LayoutConstraintItemP","title":"SnapKit.LayoutConstraintItem"},"doc://com.example.sit/documentation/App_SIT/BaseTableViewCell":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BaseTableViewCell","kind":"identifier"}],"abstract":[],"url":"\/documentation\/app_sit\/basetableviewcell","type":"topic","navigatorTitle":[{"text":"BaseTableViewCell","kind":"identifier"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell","title":"BaseTableViewCell"},"doc://com.example.sit/documentation/App_SIT/TestingViewCell/config(name:)":{"url":"\/documentation\/app_sit\/testingviewcell\/config(name:)","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell\/config(name:)","role":"symbol","kind":"symbol","type":"topic","title":"config(name:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"config","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.example.sit/SH":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/SH","title":"Swift.Hashable"},"doc://com.example.sit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/com.example.sit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"TestingViewCell","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"kind":"identifier","text":"TestingViewCell"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TestingViewCell"}]},{"value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell\/nameLabel"],"generated":true},{"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell\/awakeFromNib()","doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell\/initWithCoder:","doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell\/initWithStyle:reuseIdentifier:","doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell\/setSelected(_:animated:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell"],"kind":"relationships","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"TestingViewCell","kind":"identifier"},{"kind":"text","text":" : "},{"text":"BaseTableViewCell","kind":"typeIdentifier","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell","preciseIdentifier":"c:@M@App_SIT@objc(cs)BaseTableViewCell"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell~1setSelected(_:animated:)\/title","op":"replace","value":"setSelected:animated:"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell~1setSelected(_:animated:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setSelected:animated:"}]},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell~1nameLabel\/title","value":"nameLabel","op":"replace"},{"value":[{"text":"nameLabel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell~1nameLabel\/fragments"},{"value":"awakeFromNib","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell~1awakeFromNib()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell~1awakeFromNib()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"awakeFromNib","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell\/title","value":"TestingViewCell","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell\/fragments","value":[{"kind":"identifier","text":"TestingViewCell"}]},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell\/navigatorTitle","value":[{"text":"TestingViewCell","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableViewCell\/title","value":"BaseTableViewCell","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableViewCell\/fragments","value":[{"text":"BaseTableViewCell","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableViewCell\/navigatorTitle","op":"replace","value":[{"text":"BaseTableViewCell","kind":"identifier"}]}]}]}