{"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenRouterProtocol"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenRouterProtocol\/perform(_:from:)","interfaceLanguage":"swift"},"metadata":{"required":true,"symbolKind":"method","modules":[{"name":"App_SIT"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"perform","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:7App_SIT18ELauchScreenRouterO","kind":"typeIdentifier","text":"ELauchScreenRouter"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@App_SIT@objc(cs)LaunchScreenViewController","text":"LaunchScreenViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"perform(_:from:)","externalID":"s:7App_SIT26LaunchScreenRouterProtocolP7perform_4fromyAA06ELauchdE0O_AA0cD14ViewControllerCtF","role":"symbol","roleHeading":"Instance Method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"perform","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"segue","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ELauchScreenRouter","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/ELauchScreenRouter","preciseIdentifier":"s:7App_SIT18ELauchScreenRouterO"},{"kind":"text","text":", "},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"source","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@App_SIT@objc(cs)LaunchScreenViewController","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController","text":"LaunchScreenViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/launchscreenrouterprotocol\/perform(_:from:)"]}],"references":{"doc://com.example.sit/documentation/App_SIT/ELauchScreenRouter":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/ELauchScreenRouter","type":"topic","role":"symbol","title":"ELauchScreenRouter","url":"\/documentation\/app_sit\/elauchscreenrouter","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ELauchScreenRouter"}],"kind":"symbol","navigatorTitle":[{"text":"ELauchScreenRouter","kind":"identifier"}]},"doc://com.example.sit/documentation/App_SIT/LaunchScreenRouterProtocol":{"navigatorTitle":[{"text":"LaunchScreenRouterProtocol","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"LaunchScreenRouterProtocol","kind":"identifier"}],"url":"\/documentation\/app_sit\/launchscreenrouterprotocol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenRouterProtocol","title":"LaunchScreenRouterProtocol","type":"topic","abstract":[],"kind":"symbol"},"doc://com.example.sit/documentation/App_SIT/LaunchScreenViewController":{"navigatorTitle":[{"kind":"identifier","text":"LaunchScreenViewController"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LaunchScreenViewController"}],"url":"\/documentation\/app_sit\/launchscreenviewcontroller","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController","title":"LaunchScreenViewController","type":"topic","abstract":[],"kind":"symbol"},"doc://com.example.sit/documentation/App_SIT/LaunchScreenRouterProtocol/perform(_:from:)":{"type":"topic","title":"perform(_:from:)","kind":"symbol","required":true,"url":"\/documentation\/app_sit\/launchscreenrouterprotocol\/perform(_:from:)","abstract":[],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenRouterProtocol\/perform(_:from:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"perform"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:7App_SIT18ELauchScreenRouterO","text":"ELauchScreenRouter","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@App_SIT@objc(cs)LaunchScreenViewController","kind":"typeIdentifier","text":"LaunchScreenViewController"},{"kind":"text","text":")"}]},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"}},"variantOverrides":[{"patch":[{"value":"LaunchScreenViewController","op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController\/title"},{"value":[{"text":"LaunchScreenViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController\/navigatorTitle","value":[{"text":"LaunchScreenViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}