{"variants":[{"paths":["\/documentation\/app_sit\/launchscreenviewcontroller\/initwithcoder:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"coder"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"kind":"symbol","metadata":{"modules":[{"name":"App_SIT"}],"externalID":"c:@M@App_SIT@objc(cs)LaunchScreenViewController(im)initWithCoder:","title":"initWithCoder:","symbolKind":"method","roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController"]]},"sections":[],"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController\/initWithCoder:","interfaceLanguage":"occ"},"references":{"doc://com.example.sit/documentation/App_SIT/LaunchScreenViewController/initWithCoder:":{"type":"topic","title":"initWithCoder:","kind":"symbol","url":"\/documentation\/app_sit\/launchscreenviewcontroller\/initwithcoder:","abstract":[],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController\/initWithCoder:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}]},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/LaunchScreenViewController":{"navigatorTitle":[{"kind":"identifier","text":"LaunchScreenViewController"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LaunchScreenViewController"}],"url":"\/documentation\/app_sit\/launchscreenviewcontroller","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController","title":"LaunchScreenViewController","type":"topic","abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController\/title","value":"LaunchScreenViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController\/fragments","value":[{"text":"LaunchScreenViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController\/navigatorTitle","value":[{"text":"LaunchScreenViewController","kind":"identifier"}]}]}]}