{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/launchscreenviewcontroller\/initwithnibname:bundle:"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController\/initWithNibName:bundle:"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithNibName:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"nibNameOrNil"},{"kind":"text","text":" "},{"text":"bundle:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSBundle","preciseIdentifier":"c:objc(cs)NSBundle"},{"kind":"text","text":" *) "},{"text":"nibBundleOrNil","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController"]]},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@App_SIT@objc(cs)LaunchScreenViewController(im)initWithNibName:bundle:","title":"initWithNibName:bundle:","role":"symbol","modules":[{"name":"App_SIT"}],"navigatorTitle":[{"text":"initWithNibName:bundle:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}]},"references":{"doc://com.example.sit/documentation/App_SIT/LaunchScreenViewController":{"navigatorTitle":[{"kind":"identifier","text":"LaunchScreenViewController"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LaunchScreenViewController"}],"url":"\/documentation\/app_sit\/launchscreenviewcontroller","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController","title":"LaunchScreenViewController","type":"topic","abstract":[],"kind":"symbol"},"doc://com.example.sit/documentation/App_SIT/LaunchScreenViewController/initWithNibName:bundle:":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController\/initWithNibName:bundle:","abstract":[],"url":"\/documentation\/app_sit\/launchscreenviewcontroller\/initwithnibname:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"type":"topic","kind":"symbol","title":"initWithNibName:bundle:","role":"symbol","navigatorTitle":[{"text":"initWithNibName:bundle:","kind":"identifier"}]},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController\/title","op":"replace","value":"LaunchScreenViewController"},{"value":[{"kind":"identifier","text":"LaunchScreenViewController"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController\/navigatorTitle","value":[{"text":"LaunchScreenViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}