{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"laucher","kind":"identifier"},{"kind":"text","text":": "},{"text":"LaunchScreenRouter","kind":"typeIdentifier","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenRouter","preciseIdentifier":"s:7App_SIT18LaunchScreenRouterC"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController"]]},"metadata":{"title":"laucher","roleHeading":"Instance Property","externalID":"s:7App_SIT26LaunchScreenViewControllerC7laucherAA0cD6RouterCvp","modules":[{"name":"App_SIT"}],"role":"symbol","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"laucher","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7App_SIT18LaunchScreenRouterC","text":"LaunchScreenRouter","kind":"typeIdentifier"}]},"variants":[{"paths":["\/documentation\/app_sit\/launchscreenviewcontroller\/laucher"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController\/laucher"},"references":{"doc://com.example.sit/documentation/App_SIT/LaunchScreenViewController/laucher":{"url":"\/documentation\/app_sit\/launchscreenviewcontroller\/laucher","type":"topic","abstract":[],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController\/laucher","role":"symbol","kind":"symbol","title":"laucher","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"laucher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7App_SIT18LaunchScreenRouterC","text":"LaunchScreenRouter"}]},"doc://com.example.sit/documentation/App_SIT/LaunchScreenViewController":{"navigatorTitle":[{"kind":"identifier","text":"LaunchScreenViewController"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LaunchScreenViewController"}],"url":"\/documentation\/app_sit\/launchscreenviewcontroller","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController","title":"LaunchScreenViewController","type":"topic","abstract":[],"kind":"symbol"},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/LaunchScreenRouter":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenRouter","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LaunchScreenRouter"}],"navigatorTitle":[{"text":"LaunchScreenRouter","kind":"identifier"}],"url":"\/documentation\/app_sit\/launchscreenrouter","kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"LaunchScreenRouter"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController\/title","value":"LaunchScreenViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController\/fragments","value":[{"kind":"identifier","text":"LaunchScreenViewController"}]},{"value":[{"kind":"identifier","text":"LaunchScreenViewController"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}