{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"kind":"text","text":"()"}]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@App_SIT@objc(cs)LaunchScreenViewController(im)viewDidLoad","role":"symbol","title":"viewDidLoad()","modules":[{"name":"App_SIT"}],"navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController\/viewDidLoad()"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/launchscreenviewcontroller\/viewdidload()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/launchscreenviewcontroller\/viewdidload()"]}],"references":{"doc://com.example.sit/documentation/App_SIT/LaunchScreenViewController":{"navigatorTitle":[{"kind":"identifier","text":"LaunchScreenViewController"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LaunchScreenViewController"}],"url":"\/documentation\/app_sit\/launchscreenviewcontroller","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController","title":"LaunchScreenViewController","type":"topic","abstract":[],"kind":"symbol"},"doc://com.example.sit/documentation/App_SIT/LaunchScreenViewController/viewDidLoad()":{"url":"\/documentation\/app_sit\/launchscreenviewcontroller\/viewdidload()","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController\/viewDidLoad()","title":"viewDidLoad()","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidLoad","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic"},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"viewDidLoad","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController\/title","op":"replace","value":"LaunchScreenViewController"},{"value":[{"text":"LaunchScreenViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController\/navigatorTitle","value":[{"text":"LaunchScreenViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController~1viewDidLoad()\/title","op":"replace","value":"viewDidLoad"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController~1viewDidLoad()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}