{"metadata":{"title":"perform(_:from:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"perform"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7App_SIT18ELauchScreenRouterO","text":"ELauchScreenRouter"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"LaunchScreenViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@App_SIT@objc(cs)LaunchScreenViewController"},{"text":")","kind":"text"}],"symbolKind":"method","modules":[{"name":"App_SIT"}],"role":"symbol","externalID":"s:7App_SIT18LaunchScreenRouterC7perform_4fromyAA06ELauchdE0O_AA0cD14ViewControllerCtF"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"perform","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"segue"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/ELauchScreenRouter","text":"ELauchScreenRouter","preciseIdentifier":"s:7App_SIT18ELauchScreenRouterO","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController","preciseIdentifier":"c:@M@App_SIT@objc(cs)LaunchScreenViewController","text":"LaunchScreenViewController"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"LaunchScreenRouterProtocol.perform(_:from:)","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenRouter"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/launchscreenrouter\/perform(_:from:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenRouter\/perform(_:from:)"},"kind":"symbol","references":{"doc://com.example.sit/documentation/App_SIT/LaunchScreenViewController":{"navigatorTitle":[{"kind":"identifier","text":"LaunchScreenViewController"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LaunchScreenViewController"}],"url":"\/documentation\/app_sit\/launchscreenviewcontroller","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController","title":"LaunchScreenViewController","type":"topic","abstract":[],"kind":"symbol"},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/ELauchScreenRouter":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/ELauchScreenRouter","type":"topic","role":"symbol","title":"ELauchScreenRouter","url":"\/documentation\/app_sit\/elauchscreenrouter","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ELauchScreenRouter"}],"kind":"symbol","navigatorTitle":[{"text":"ELauchScreenRouter","kind":"identifier"}]},"doc://com.example.sit/documentation/App_SIT/LaunchScreenRouter":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenRouter","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LaunchScreenRouter"}],"navigatorTitle":[{"text":"LaunchScreenRouter","kind":"identifier"}],"url":"\/documentation\/app_sit\/launchscreenrouter","kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"LaunchScreenRouter"},"doc://com.example.sit/documentation/App_SIT/LaunchScreenRouter/perform(_:from:)":{"type":"topic","title":"perform(_:from:)","abstract":[],"url":"\/documentation\/app_sit\/launchscreenrouter\/perform(_:from:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"perform"},{"kind":"text","text":"("},{"preciseIdentifier":"s:7App_SIT18ELauchScreenRouterO","text":"ELauchScreenRouter","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@App_SIT@objc(cs)LaunchScreenViewController","text":"LaunchScreenViewController"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenRouter\/perform(_:from:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController\/title","value":"LaunchScreenViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController\/fragments","value":[{"text":"LaunchScreenViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController\/navigatorTitle","value":[{"text":"LaunchScreenViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}