{"abstract":[{"type":"text","text":"Inherited from "},{"code":"HomeScreenRouterProtocol.perform(_:from:)","type":"codeVoice"},{"type":"text","text":"."}],"metadata":{"roleHeading":"Instance Method","externalID":"s:7App_SIT14HomeViewRouterC7perform_4fromyAA011EHomeScreenE0O_AA0cD10ControllerCtF","role":"symbol","title":"perform(_:from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"perform"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"EHomeScreenRouter","preciseIdentifier":"s:7App_SIT17EHomeScreenRouterO"},{"kind":"text","text":", "},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HomeViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@App_SIT@objc(cs)HomeViewController"},{"kind":"text","text":")"}],"symbolKind":"method","modules":[{"name":"App_SIT"}]},"variants":[{"paths":["\/documentation\/app_sit\/homeviewrouter\/perform(_:from:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewRouter\/perform(_:from:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"perform"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"segue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EHomeScreenRouter","preciseIdentifier":"s:7App_SIT17EHomeScreenRouterO","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/EHomeScreenRouter"},{"kind":"text","text":", "},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"source"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"HomeViewController","preciseIdentifier":"c:@M@App_SIT@objc(cs)HomeViewController","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewRouter"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/EHomeScreenRouter":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EHomeScreenRouter"}],"title":"EHomeScreenRouter","type":"topic","url":"\/documentation\/app_sit\/ehomescreenrouter","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/EHomeScreenRouter","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"EHomeScreenRouter"}],"abstract":[],"role":"symbol"},"doc://com.example.sit/documentation/App_SIT/HomeViewRouter/perform(_:from:)":{"url":"\/documentation\/app_sit\/homeviewrouter\/perform(_:from:)","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewRouter\/perform(_:from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"perform"},{"kind":"text","text":"("},{"preciseIdentifier":"s:7App_SIT17EHomeScreenRouterO","kind":"typeIdentifier","text":"EHomeScreenRouter"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HomeViewController","preciseIdentifier":"c:@M@App_SIT@objc(cs)HomeViewController"},{"kind":"text","text":")"}],"role":"symbol","title":"perform(_:from:)","type":"topic","abstract":[],"kind":"symbol"},"doc://com.example.sit/documentation/App_SIT/HomeViewRouter":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HomeViewRouter"}],"type":"topic","abstract":[],"role":"symbol","title":"HomeViewRouter","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewRouter","url":"\/documentation\/app_sit\/homeviewrouter","navigatorTitle":[{"kind":"identifier","text":"HomeViewRouter"}],"kind":"symbol"},"doc://com.example.sit/documentation/App_SIT/HomeViewController":{"role":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController","navigatorTitle":[{"text":"HomeViewController","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"HomeViewController"},{"text":" class is responsible for managing the home screen of the app.","type":"text"}],"url":"\/documentation\/app_sit\/homeviewcontroller","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HomeViewController","kind":"identifier"}],"title":"HomeViewController","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/title","op":"replace","value":"HomeViewController"},{"op":"replace","value":[{"kind":"identifier","text":"HomeViewController"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/fragments"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"HomeViewController"}]}]}]}