{"variants":[{"paths":["\/documentation\/app_sit\/homescreenrouterprotocol\/perform(_:from:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"s:7App_SIT24HomeScreenRouterProtocolP7perform_4fromyAA05EHomedE0O_AA0C14ViewControllerCtF","title":"perform(_:from:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"perform"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:7App_SIT17EHomeScreenRouterO","text":"EHomeScreenRouter","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"text":"HomeViewController","preciseIdentifier":"c:@M@App_SIT@objc(cs)HomeViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","modules":[{"name":"App_SIT"}],"symbolKind":"method","required":true,"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"perform"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"segue"},{"text":": ","kind":"text"},{"text":"EHomeScreenRouter","preciseIdentifier":"s:7App_SIT17EHomeScreenRouterO","kind":"typeIdentifier","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/EHomeScreenRouter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"text":"source","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController","preciseIdentifier":"c:@M@App_SIT@objc(cs)HomeViewController","text":"HomeViewController"},{"text":")","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeScreenRouterProtocol"]]},"sections":[],"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeScreenRouterProtocol\/perform(_:from:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.example.sit/documentation/App_SIT/HomeScreenRouterProtocol/perform(_:from:)":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeScreenRouterProtocol\/perform(_:from:)","type":"topic","role":"symbol","title":"perform(_:from:)","abstract":[],"url":"\/documentation\/app_sit\/homescreenrouterprotocol\/perform(_:from:)","kind":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"perform","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:7App_SIT17EHomeScreenRouterO","text":"EHomeScreenRouter","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@App_SIT@objc(cs)HomeViewController","text":"HomeViewController"},{"text":")","kind":"text"}]},"doc://com.example.sit/documentation/App_SIT/HomeScreenRouterProtocol":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"HomeScreenRouterProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeScreenRouterProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HomeScreenRouterProtocol"}],"type":"topic","url":"\/documentation\/app_sit\/homescreenrouterprotocol","title":"HomeScreenRouterProtocol","abstract":[]},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/EHomeScreenRouter":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EHomeScreenRouter"}],"title":"EHomeScreenRouter","type":"topic","url":"\/documentation\/app_sit\/ehomescreenrouter","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/EHomeScreenRouter","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"EHomeScreenRouter"}],"abstract":[],"role":"symbol"},"doc://com.example.sit/documentation/App_SIT/HomeViewController":{"role":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController","navigatorTitle":[{"text":"HomeViewController","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"HomeViewController"},{"text":" class is responsible for managing the home screen of the app.","type":"text"}],"url":"\/documentation\/app_sit\/homeviewcontroller","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HomeViewController","kind":"identifier"}],"title":"HomeViewController","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/title","value":"HomeViewController"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/fragments","op":"replace","value":[{"text":"HomeViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/navigatorTitle","value":[{"text":"HomeViewController","kind":"identifier"}]}]}]}