{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/appdelegate\/application(_:didfinishlaunchingwithoptions:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/appdelegate\/application(_:didfinishlaunchingwithoptions:)"]}],"metadata":{"externalID":"c:@M@App_SIT@objc(cs)AppDelegate(im)application:didFinishLaunchingWithOptions:","roleHeading":"Instance Method","title":"application(_:didFinishLaunchingWithOptions:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFinishLaunchingWithOptions"},{"kind":"text","text":": ["},{"text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@UIApplicationLaunchOptionsKey","text":"LaunchOptionsKey"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"application:didFinishLaunchingWithOptions:"}],"modules":[{"name":"App_SIT"}],"role":"symbol"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIApplicationDelegate.application(_:didFinishLaunchingWithOptions:)"},{"text":".","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"application","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFinishLaunchingWithOptions"},{"kind":"text","text":" "},{"text":"launchOptions","kind":"internalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"LaunchOptionsKey","preciseIdentifier":"c:@T@UIApplicationLaunchOptionsKey","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"languages":["swift"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate\/application(_:didFinishLaunchingWithOptions:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate"]]},"references":{"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/AppDelegate/application(_:didFinishLaunchingWithOptions:)":{"title":"application(_:didFinishLaunchingWithOptions:)","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"kind":"text","text":", "},{"text":"didFinishLaunchingWithOptions","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@UIApplicationLaunchOptionsKey","text":"LaunchOptionsKey","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","url":"\/documentation\/app_sit\/appdelegate\/application(_:didfinishlaunchingwithoptions:)","type":"topic","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate\/application(_:didFinishLaunchingWithOptions:)","navigatorTitle":[{"text":"application:didFinishLaunchingWithOptions:","kind":"identifier"}]},"doc://com.example.sit/documentation/App_SIT/AppDelegate":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AppDelegate","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AppDelegate"}],"url":"\/documentation\/app_sit\/appdelegate","kind":"symbol","title":"AppDelegate"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"application:didFinishLaunchingWithOptions:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"application:didFinishLaunchingWithOptions:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"application:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"text":" *) ","kind":"text"},{"text":"application","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishLaunchingWithOptions:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,id>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"launchOptions"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate~1application(_:didFinishLaunchingWithOptions:)\/title","value":"application:didFinishLaunchingWithOptions:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"application:didFinishLaunchingWithOptions:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate~1application(_:didFinishLaunchingWithOptions:)\/fragments"},{"value":"AppDelegate","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AppDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AppDelegate"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}