{"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/app_sit\/appdelegate\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate\/init","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"init","externalID":"c:@M@App_SIT@objc(cs)AppDelegate(im)init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"modules":[{"name":"App_SIT"}]},"references":{"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/AppDelegate":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AppDelegate","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AppDelegate"}],"url":"\/documentation\/app_sit\/appdelegate","kind":"symbol","title":"AppDelegate"},"doc://com.example.sit/documentation/App_SIT/AppDelegate/init":{"abstract":[],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate\/init","kind":"symbol","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/app_sit\/appdelegate\/init","title":"init","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate\/title","op":"replace","value":"AppDelegate"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate\/fragments","op":"replace","value":[{"text":"AppDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AppDelegate"}]}]}]}