{"metadata":{"role":"symbol","roleHeading":"Type Method","symbolKind":"method","modules":[{"name":"App_SIT","relatedModules":["UIKit"]}],"extendedModule":"UIKit","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"main","kind":"identifier"},{"text":"()","kind":"text"}],"externalID":"s:So21UIApplicationDelegateP5UIKitE4mainyyFZ::SYNTHESIZED::c:@M@App_SIT@objc(cs)AppDelegate","title":"main()"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UIApplicationDelegate.main()"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate","doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate\/UIApplicationDelegate-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"text":"@preconcurrency","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"main"},{"kind":"text","text":"()"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/appdelegate\/main()"]}],"sections":[],"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate\/main()","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/AppDelegate":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AppDelegate","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AppDelegate"}],"url":"\/documentation\/app_sit\/appdelegate","kind":"symbol","title":"AppDelegate"},"doc://com.example.sit/documentation/App_SIT/AppDelegate/UIApplicationDelegate-Implementations":{"abstract":[],"url":"\/documentation\/app_sit\/appdelegate\/uiapplicationdelegate-implementations","role":"collectionGroup","title":"UIApplicationDelegate Implementations","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate\/UIApplicationDelegate-Implementations","type":"topic","kind":"article"},"doc://com.example.sit/documentation/App_SIT/AppDelegate/main()":{"abstract":[],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/app_sit\/appdelegate\/main()","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate\/main()","title":"main()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"main","kind":"identifier"},{"text":"()","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"AppDelegate","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate\/title"},{"value":[{"text":"AppDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate\/navigatorTitle","value":[{"text":"AppDelegate","kind":"identifier"}]}]}]}