{"kind":"article","hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate\/main()"],"generated":true}],"sections":[],"variants":[{"paths":["\/documentation\/app_sit\/appdelegate\/uiapplicationdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate\/UIApplicationDelegate-Implementations","interfaceLanguage":"swift"},"metadata":{"title":"UIApplicationDelegate Implementations","roleHeading":"API Collection","modules":[{"name":"App_SIT"}],"role":"collectionGroup"},"references":{"doc://com.example.sit/documentation/App_SIT/AppDelegate":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AppDelegate","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AppDelegate"}],"url":"\/documentation\/app_sit\/appdelegate","kind":"symbol","title":"AppDelegate"},"doc://com.example.sit/documentation/App_SIT/AppDelegate/main()":{"abstract":[],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/app_sit\/appdelegate\/main()","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate\/main()","title":"main()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"main","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"AppDelegate","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"AppDelegate"}]},{"value":[{"kind":"identifier","text":"AppDelegate"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate\/navigatorTitle","op":"replace"}]}]}