{"kind":"symbol","metadata":{"title":"window","externalID":"c:@M@App_SIT@objc(cs)AppDelegate(py)window","role":"symbol","symbolKind":"property","modules":[{"name":"App_SIT"}],"navigatorTitle":[{"kind":"identifier","text":"window"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"window","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/appdelegate\/window"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/appdelegate\/window"]}],"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate\/window","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIApplicationDelegate.window"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"window"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIWindow","text":"UIWindow"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate"]]},"references":{"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/AppDelegate/window":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"window"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIWindow","text":"UIWindow"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate\/window","type":"topic","abstract":[],"title":"window","role":"symbol","url":"\/documentation\/app_sit\/appdelegate\/window","kind":"symbol","navigatorTitle":[{"text":"window","kind":"identifier"}]},"doc://com.example.sit/documentation/App_SIT/AppDelegate":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AppDelegate","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AppDelegate"}],"url":"\/documentation\/app_sit\/appdelegate","kind":"symbol","title":"AppDelegate"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"window","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"window","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIWindow","text":"UIWindow"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"window"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"window","op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate~1window\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate~1window\/fragments","value":[{"kind":"identifier","text":"window"}]},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate\/title","value":"AppDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate\/fragments","op":"replace","value":[{"text":"AppDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate\/navigatorTitle","value":[{"text":"AppDelegate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}