{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell\/identifier"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","roleHeading":"Type Property","symbolKind":"property","title":"identifier","modules":[{"name":"App_SIT"}],"externalID":"s:7App_SIT17BaseTableViewCellC10identifierSSvpZ","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/basetableviewcell\/identifier"]}],"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.example.sit/documentation/App_SIT":{"abstract":[],"title":"App_SIT","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/app_sit","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT"},"doc://com.example.sit/documentation/App_SIT/BaseTableViewCell":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BaseTableViewCell","kind":"identifier"}],"abstract":[],"url":"\/documentation\/app_sit\/basetableviewcell","type":"topic","navigatorTitle":[{"text":"BaseTableViewCell","kind":"identifier"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell","title":"BaseTableViewCell"},"doc://com.example.sit/documentation/App_SIT/BaseTableViewCell/identifier":{"abstract":[],"title":"identifier","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/app_sit\/basetableviewcell\/identifier","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell\/identifier","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"identifier","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"BaseTableViewCell","op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableViewCell\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableViewCell\/fragments","value":[{"kind":"identifier","text":"BaseTableViewCell"}]},{"op":"replace","value":[{"text":"BaseTableViewCell","kind":"identifier"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableViewCell\/navigatorTitle"}]}]}