{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithStyle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@UITableViewCellStyle","kind":"typeIdentifier","text":"UITableViewCellStyle"},{"text":") ","kind":"text"},{"text":"style","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reuseIdentifier:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"reuseIdentifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/app_sit\/basetableviewcell\/initwithstyle:reuseidentifier:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell\/initWithStyle:reuseIdentifier:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"externalID":"c:@M@App_SIT@objc(cs)BaseTableViewCell(im)initWithStyle:reuseIdentifier:","platforms":[{"introducedAt":"3.0","deprecated":false,"beta":false,"name":"iOS","unavailable":false},{"introducedAt":"3.0","unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS"},{"beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"3.0"}],"modules":[{"name":"App_SIT"}],"role":"symbol","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"navigatorTitle":[{"text":"initWithStyle:reuseIdentifier:","kind":"identifier"}],"title":"initWithStyle:reuseIdentifier:","roleHeading":"Instance Method"},"references":{"doc://com.example.sit/documentation/App_SIT/BaseTableViewCell":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BaseTableViewCell","kind":"identifier"}],"abstract":[],"url":"\/documentation\/app_sit\/basetableviewcell","type":"topic","navigatorTitle":[{"text":"BaseTableViewCell","kind":"identifier"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell","title":"BaseTableViewCell"},"doc://com.example.sit/documentation/App_SIT/BaseTableViewCell/initWithStyle:reuseIdentifier:":{"title":"initWithStyle:reuseIdentifier:","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell\/initWithStyle:reuseIdentifier:","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"url":"\/documentation\/app_sit\/basetableviewcell\/initwithstyle:reuseidentifier:","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"text":"initWithStyle:reuseIdentifier:","kind":"identifier"}]},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"BaseTableViewCell","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableViewCell\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableViewCell\/fragments","value":[{"text":"BaseTableViewCell","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableViewCell\/navigatorTitle","value":[{"text":"BaseTableViewCell","kind":"identifier"}],"op":"replace"}]}]}