{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"coder"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/basetableviewcell\/initwithcoder:"]}],"metadata":{"modules":[{"name":"App_SIT"}],"externalID":"c:@M@App_SIT@objc(cs)BaseTableViewCell(im)initWithCoder:","role":"symbol","title":"initWithCoder:","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell\/initWithCoder:"},"kind":"symbol","references":{"doc://com.example.sit/documentation/App_SIT/BaseTableViewCell":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BaseTableViewCell","kind":"identifier"}],"abstract":[],"url":"\/documentation\/app_sit\/basetableviewcell","type":"topic","navigatorTitle":[{"text":"BaseTableViewCell","kind":"identifier"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell","title":"BaseTableViewCell"},"doc://com.example.sit/documentation/App_SIT/BaseTableViewCell/initWithCoder:":{"type":"topic","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"title":"initWithCoder:","role":"symbol","abstract":[],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell\/initWithCoder:","kind":"symbol","url":"\/documentation\/app_sit\/basetableviewcell\/initwithcoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"BaseTableViewCell","op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableViewCell\/title"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableViewCell\/fragments","op":"replace","value":[{"text":"BaseTableViewCell","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"BaseTableViewCell"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableViewCell\/navigatorTitle"}]}]}