{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"title":"setSelected(_:animated:)","externalID":"c:@M@App_SIT@objc(cs)BaseTableViewCell(im)setSelected:animated:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setSelected","kind":"identifier"},{"kind":"text","text":"("},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"animated","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"setSelected:animated:","kind":"identifier"}],"modules":[{"name":"App_SIT"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setSelected","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"selected"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell\/setSelected(_:animated:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/basetableviewcell\/setselected(_:animated:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/basetableviewcell\/setselected(_:animated:)"]}],"kind":"symbol","references":{"doc://com.example.sit/documentation/App_SIT/BaseTableViewCell/setSelected(_:animated:)":{"url":"\/documentation\/app_sit\/basetableviewcell\/setselected(_:animated:)","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell\/setSelected(_:animated:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setSelected","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"animated"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"abstract":[],"type":"topic","navigatorTitle":[{"text":"setSelected:animated:","kind":"identifier"}],"title":"setSelected(_:animated:)"},"doc://com.example.sit/documentation/App_SIT/BaseTableViewCell":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BaseTableViewCell","kind":"identifier"}],"abstract":[],"url":"\/documentation\/app_sit\/basetableviewcell","type":"topic","navigatorTitle":[{"text":"BaseTableViewCell","kind":"identifier"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell","title":"BaseTableViewCell"},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"setSelected:animated:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setSelected:animated:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"setSelected:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"selected","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"animated:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"animated"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableViewCell~1setSelected(_:animated:)\/title","value":"setSelected:animated:"},{"value":[{"text":"- ","kind":"text"},{"text":"setSelected:animated:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableViewCell~1setSelected(_:animated:)\/fragments","op":"replace"},{"op":"replace","value":"BaseTableViewCell","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableViewCell\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableViewCell\/fragments","value":[{"text":"BaseTableViewCell","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableViewCell\/navigatorTitle","value":[{"kind":"identifier","text":"BaseTableViewCell"}]}]}]}