{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView\/contentSize"},"metadata":{"navigatorTitle":[{"text":"contentSize","kind":"identifier"}],"externalID":"c:@M@App_SIT@objc(cs)BaseTableView(py)contentSize","modules":[{"name":"App_SIT"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contentSize"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","title":"contentSize"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contentSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/basetableview\/contentsize"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/basetableview\/contentsize"]}],"kind":"symbol","references":{"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/BaseTableView":{"type":"topic","abstract":[],"url":"\/documentation\/app_sit\/basetableview","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView","navigatorTitle":[{"text":"BaseTableView","kind":"identifier"}],"title":"BaseTableView","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BaseTableView"}]},"doc://com.example.sit/documentation/App_SIT/BaseTableView/contentSize":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"contentSize"}],"url":"\/documentation\/app_sit\/basetableview\/contentsize","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contentSize"},{"text":": ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","title":"contentSize","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView\/contentSize","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"contentSize"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"contentSize","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contentSize"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView\/title","value":"BaseTableView"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView\/fragments","value":[{"text":"BaseTableView","kind":"identifier"}],"op":"replace"},{"value":[{"text":"BaseTableView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView~1contentSize\/title","value":"contentSize"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView~1contentSize\/fragments","op":"replace","value":[{"text":"contentSize","kind":"identifier"}]}]}]}