{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithCoder:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":" *) "},{"text":"coder","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView"]]},"metadata":{"symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"externalID":"c:@M@App_SIT@objc(cs)BaseTableView(im)initWithCoder:","roleHeading":"Instance Method","modules":[{"name":"App_SIT"}],"fragments":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}],"title":"initWithCoder:"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView\/initWithCoder:","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/basetableview\/initwithcoder:"]}],"references":{"doc://com.example.sit/documentation/App_SIT/BaseTableView/initWithCoder:":{"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/app_sit\/basetableview\/initwithcoder:","abstract":[],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"title":"initWithCoder:","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView\/initWithCoder:"},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/BaseTableView":{"type":"topic","abstract":[],"url":"\/documentation\/app_sit\/basetableview","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView","navigatorTitle":[{"text":"BaseTableView","kind":"identifier"}],"title":"BaseTableView","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BaseTableView"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"BaseTableView","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView\/title"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView\/fragments","op":"replace","value":[{"text":"BaseTableView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView\/navigatorTitle","value":[{"text":"BaseTableView","kind":"identifier"}],"op":"replace"}]}]}