{"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView\/initWithFrame:style:"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithFrame:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":") ","kind":"text"},{"text":"frame","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"style:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@UITableViewStyle","text":"UITableViewStyle","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"style"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/basetableview\/initwithframe:style:"]}],"sections":[],"kind":"symbol","metadata":{"externalID":"c:@M@App_SIT@objc(cs)BaseTableView(im)initWithFrame:style:","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:style:"}],"roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"text":"initWithFrame:style:","kind":"identifier"}],"title":"initWithFrame:style:","modules":[{"name":"App_SIT"}],"role":"symbol","symbolKind":"method"},"references":{"doc://com.example.sit/documentation/App_SIT/BaseTableView/initWithFrame:style:":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:style:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:style:"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView\/initWithFrame:style:","role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/app_sit\/basetableview\/initwithframe:style:","title":"initWithFrame:style:"},"doc://com.example.sit/documentation/App_SIT/BaseTableView":{"type":"topic","abstract":[],"url":"\/documentation\/app_sit\/basetableview","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView","navigatorTitle":[{"text":"BaseTableView","kind":"identifier"}],"title":"BaseTableView","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BaseTableView"}]},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView\/title","value":"BaseTableView"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView\/fragments","value":[{"kind":"identifier","text":"BaseTableView"}]},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView\/navigatorTitle","value":[{"kind":"identifier","text":"BaseTableView"}],"op":"replace"}]}]}