{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/app_sit\/basetableview\/reloaddata()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/app_sit\/basetableview\/reloaddata()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView\/reloadData()","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"reloadData","kind":"identifier"}],"role":"symbol","externalID":"c:@M@App_SIT@objc(cs)BaseTableView(im)reloadData","title":"reloadData()","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"reloadData"},{"text":"()","kind":"text"}],"modules":[{"name":"App_SIT"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reloadData"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/BaseTableView":{"type":"topic","abstract":[],"url":"\/documentation\/app_sit\/basetableview","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView","navigatorTitle":[{"text":"BaseTableView","kind":"identifier"}],"title":"BaseTableView","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BaseTableView"}]},"doc://com.example.sit/documentation/App_SIT/BaseTableView/reloadData()":{"title":"reloadData()","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView\/reloadData()","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reloadData"},{"text":"()","kind":"text"}],"url":"\/documentation\/app_sit\/basetableview\/reloaddata()","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"reloadData","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"reloadData","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"reloadData","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"reloadData","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView\/title","value":"BaseTableView"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView\/fragments","value":[{"text":"BaseTableView","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView\/navigatorTitle","value":[{"text":"BaseTableView","kind":"identifier"}]},{"op":"replace","value":"reloadData","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView~1reloadData()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"reloadData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView~1reloadData()\/fragments","op":"replace"}]}]}