{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"text":"initWithNibName:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"nibNameOrNil","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bundle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle","text":"NSBundle"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nibBundleOrNil"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController"]]},"metadata":{"role":"symbol","modules":[{"name":"App_SIT"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithNibName:bundle:","kind":"identifier"}],"title":"initWithNibName:bundle:","roleHeading":"Instance Method","externalID":"c:@M@App_SIT@objc(cs)BaseViewController(im)initWithNibName:bundle:","symbolKind":"method","navigatorTitle":[{"text":"initWithNibName:bundle:","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/baseviewcontroller\/initwithnibname:bundle:"]}],"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController\/initWithNibName:bundle:","interfaceLanguage":"occ"},"references":{"doc://com.example.sit/documentation/App_SIT/BaseViewController":{"role":"symbol","abstract":[{"type":"text","text":"Base ViewController for manage whole project UIViewController"}],"navigatorTitle":[{"text":"BaseViewController","kind":"identifier"}],"title":"BaseViewController","type":"topic","url":"\/documentation\/app_sit\/baseviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BaseViewController","kind":"identifier"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController","kind":"symbol"},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/BaseViewController/initWithNibName:bundle:":{"kind":"symbol","abstract":[],"title":"initWithNibName:bundle:","url":"\/documentation\/app_sit\/baseviewcontroller\/initwithnibname:bundle:","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController\/initWithNibName:bundle:","type":"topic","role":"symbol","navigatorTitle":[{"text":"initWithNibName:bundle:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"text":"initWithNibName:bundle:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController\/title","value":"BaseViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController\/fragments","value":[{"text":"BaseViewController","kind":"identifier"}]},{"value":[{"text":"BaseViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}