{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":" *) ","kind":"text"},{"text":"coder","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController"]]},"sections":[],"metadata":{"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"modules":[{"name":"App_SIT"}],"title":"initWithCoder:","externalID":"c:@M@App_SIT@objc(cs)BaseViewController(im)initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method"},"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController\/initWithCoder:","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/app_sit\/baseviewcontroller\/initwithcoder:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.example.sit/documentation/App_SIT/BaseViewController/initWithCoder:":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController\/initWithCoder:","role":"symbol","title":"initWithCoder:","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/app_sit\/baseviewcontroller\/initwithcoder:","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}]},"doc://com.example.sit/documentation/App_SIT/BaseViewController":{"role":"symbol","abstract":[{"type":"text","text":"Base ViewController for manage whole project UIViewController"}],"navigatorTitle":[{"text":"BaseViewController","kind":"identifier"}],"title":"BaseViewController","type":"topic","url":"\/documentation\/app_sit\/baseviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BaseViewController","kind":"identifier"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController","kind":"symbol"},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"BaseViewController","op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController\/fragments","value":[{"kind":"identifier","text":"BaseViewController"}]},{"value":[{"text":"BaseViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController\/navigatorTitle","op":"replace"}]}]}