{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/app_sit\/baseviewcontroller\/shouldload()"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"shouldLoad","kind":"identifier"},{"kind":"text","text":"()"}],"modules":[{"name":"App_SIT"}],"externalID":"s:7App_SIT18BaseViewControllerC10shouldLoadyyF","role":"symbol","symbolKind":"method","roleHeading":"Instance Method","title":"shouldLoad()"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController\/shouldLoad()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"shouldLoad","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"text":"Delay 0.5 after ViewDidLoad being called.","type":"text"}],"sections":[],"references":{"doc://com.example.sit/documentation/App_SIT/BaseViewController":{"role":"symbol","abstract":[{"type":"text","text":"Base ViewController for manage whole project UIViewController"}],"navigatorTitle":[{"text":"BaseViewController","kind":"identifier"}],"title":"BaseViewController","type":"topic","url":"\/documentation\/app_sit\/baseviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BaseViewController","kind":"identifier"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController","kind":"symbol"},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/BaseViewController/shouldLoad()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"shouldLoad","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController\/shouldLoad()","role":"symbol","title":"shouldLoad()","abstract":[{"text":"Delay 0.5 after ViewDidLoad being called.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/app_sit\/baseviewcontroller\/shouldload()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"BaseViewController","op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController\/title"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController\/fragments","op":"replace","value":[{"text":"BaseViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController\/navigatorTitle","value":[{"kind":"identifier","text":"BaseViewController"}]}]}]}