{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/app_sit\/baseviewcontroller\/viewdidload()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit\/baseviewcontroller\/viewdidload()"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController\/viewDidLoad()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.example.sit\/documentation\/App_SIT","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController"]]},"sections":[],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"App_SIT"}],"externalID":"c:@M@App_SIT@objc(cs)BaseViewController(im)viewDidLoad","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"symbolKind":"method","role":"symbol","title":"viewDidLoad()"},"references":{"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/BaseViewController/viewDidLoad()":{"url":"\/documentation\/app_sit\/baseviewcontroller\/viewdidload()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController\/viewDidLoad()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","title":"viewDidLoad()","abstract":[]},"doc://com.example.sit/documentation/App_SIT/BaseViewController":{"role":"symbol","abstract":[{"type":"text","text":"Base ViewController for manage whole project UIViewController"}],"navigatorTitle":[{"text":"BaseViewController","kind":"identifier"}],"title":"BaseViewController","type":"topic","url":"\/documentation\/app_sit\/baseviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BaseViewController","kind":"identifier"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"viewDidLoad"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"viewDidLoad"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController~1viewDidLoad()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController\/title","value":"BaseViewController"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"BaseViewController"}]},{"value":[{"kind":"identifier","text":"BaseViewController"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController\/navigatorTitle","op":"replace"}]}]}