{"metadata":{"externalID":"App_SIT","roleHeading":"Application","symbolKind":"module","modules":[{"name":"App_SIT"}],"title":"App_SIT","role":"collection"},"topicSections":[{"anchor":"Articles","title":"Articles","generated":true,"identifiers":["doc:\/\/com.example.sit\/documentation\/App-SIT\/FeatureDocumentation","doc:\/\/com.example.sit\/documentation\/App-SIT\/HomeDocumentation"]},{"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController","doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController","doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController","doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewModel","doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewRouter","doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenRouter","doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController","doc:\/\/com.example.sit\/documentation\/App_SIT\/Launcher","doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController","doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate","doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell","doc:\/\/com.example.sit\/documentation\/App_SIT\/Utilities"],"title":"Classes","anchor":"Classes","generated":true},{"anchor":"Protocols","identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeScreenRouterProtocol","doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenRouterProtocol"],"generated":true,"title":"Protocols"},{"generated":true,"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/ColorResource","doc:\/\/com.example.sit\/documentation\/App_SIT\/Env","doc:\/\/com.example.sit\/documentation\/App_SIT\/ImageResource"],"anchor":"Structures","title":"Structures"},{"generated":true,"anchor":"Variables","title":"Variables","identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/BASE_URL"]},{"generated":true,"anchor":"Functions","title":"Functions","identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/print(_:separator:terminator:)"]},{"anchor":"Enumerations","generated":true,"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/EHomeScreenRouter","doc:\/\/com.example.sit\/documentation\/App_SIT\/ELauchScreenRouter","doc:\/\/com.example.sit\/documentation\/App_SIT\/EStoryboard","doc:\/\/com.example.sit\/documentation\/App_SIT\/EViewController"],"title":"Enumerations"},{"generated":true,"title":"Extended Modules","anchor":"Extended-Modules","identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/SwiftUICore","doc:\/\/com.example.sit\/documentation\/App_SIT\/UIKit"]}],"sections":[],"variants":[{"paths":["\/documentation\/app_sit"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/app_sit"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.example.sit\/documentation\/App_SIT","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[[]]},"references":{"doc://com.example.sit/documentation/App_SIT/Utilities":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Utilities"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/Utilities","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Utilities"}],"url":"\/documentation\/app_sit\/utilities","kind":"symbol","title":"Utilities"},"doc://com.example.sit/documentation/App_SIT/Launcher":{"type":"topic","abstract":[],"title":"Launcher","url":"\/documentation\/app_sit\/launcher","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Launcher"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/Launcher","navigatorTitle":[{"text":"Launcher","kind":"identifier"}]},"doc://com.example.sit/documentation/App_SIT/ColorResource":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ColorResource"}],"abstract":[{"text":"A color resource.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/ColorResource","role":"symbol","navigatorTitle":[{"text":"ColorResource","kind":"identifier"}],"url":"\/documentation\/app_sit\/colorresource","kind":"symbol","title":"ColorResource"},"doc://com.example.sit/documentation/App_SIT/LaunchScreenViewController":{"navigatorTitle":[{"kind":"identifier","text":"LaunchScreenViewController"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LaunchScreenViewController"}],"url":"\/documentation\/app_sit\/launchscreenviewcontroller","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController","title":"LaunchScreenViewController","type":"topic","abstract":[],"kind":"symbol"},"doc://com.example.sit/documentation/App_SIT/AppDelegate":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AppDelegate","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AppDelegate"}],"url":"\/documentation\/app_sit\/appdelegate","kind":"symbol","title":"AppDelegate"},"doc://com.example.sit/documentation/App_SIT/UIKit":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/UIKit","url":"\/documentation\/app_sit\/uikit","role":"collection","abstract":[],"type":"topic","title":"UIKit","kind":"symbol"},"doc://com.example.sit/documentation/App_SIT/TestingViewCell":{"navigatorTitle":[{"kind":"identifier","text":"TestingViewCell"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TestingViewCell","kind":"identifier"}],"url":"\/documentation\/app_sit\/testingviewcell","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell","title":"TestingViewCell","type":"topic","abstract":[],"kind":"symbol"},"doc://com.example.sit/documentation/App_SIT/Env":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Env"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/Env","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Env"}],"url":"\/documentation\/app_sit\/env","kind":"symbol","title":"Env"},"doc://com.example.sit/documentation/App_SIT/EStoryboard":{"type":"topic","url":"\/documentation\/app_sit\/estoryboard","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"EStoryboard","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"EStoryboard"}],"kind":"symbol","title":"EStoryboard","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/EStoryboard"},"doc://com.example.sit/documentation/App_SIT/FeatureOneViewController":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController","type":"topic","navigatorTitle":[{"text":"FeatureOneViewController","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FeatureOneViewController","kind":"identifier"}],"abstract":[],"url":"\/documentation\/app_sit\/featureoneviewcontroller","title":"FeatureOneViewController","role":"symbol"},"doc://com.example.sit/documentation/App_SIT/LaunchScreenRouterProtocol":{"navigatorTitle":[{"text":"LaunchScreenRouterProtocol","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"LaunchScreenRouterProtocol","kind":"identifier"}],"url":"\/documentation\/app_sit\/launchscreenrouterprotocol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenRouterProtocol","title":"LaunchScreenRouterProtocol","type":"topic","abstract":[],"kind":"symbol"},"doc://com.example.sit/documentation/App_SIT/LoadingViewController":{"url":"\/documentation\/app_sit\/loadingviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoadingViewController"}],"type":"topic","navigatorTitle":[{"text":"LoadingViewController","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController","role":"symbol","kind":"symbol","title":"LoadingViewController"},"doc://com.example.sit/documentation/App_SIT/HomeViewController":{"role":"symbol","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController","navigatorTitle":[{"text":"HomeViewController","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"HomeViewController"},{"text":" class is responsible for managing the home screen of the app.","type":"text"}],"url":"\/documentation\/app_sit\/homeviewcontroller","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HomeViewController","kind":"identifier"}],"title":"HomeViewController","type":"topic"},"doc://com.example.sit/documentation/App_SIT/BaseTableView":{"type":"topic","abstract":[],"url":"\/documentation\/app_sit\/basetableview","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView","navigatorTitle":[{"text":"BaseTableView","kind":"identifier"}],"title":"BaseTableView","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BaseTableView"}]},"doc://com.example.sit/documentation/App_SIT/print(_:separator:terminator:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"print"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"..., ","kind":"text"},{"text":"separator","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"terminator","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/print(_:separator:terminator:)","role":"symbol","url":"\/documentation\/app_sit\/print(_:separator:terminator:)","kind":"symbol","title":"print(_:separator:terminator:)"},"doc://com.example.sit/documentation/App_SIT/SceneDelegate":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate","url":"\/documentation\/app_sit\/scenedelegate","kind":"symbol","title":"SceneDelegate","role":"symbol","navigatorTitle":[{"text":"SceneDelegate","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SceneDelegate","kind":"identifier"}]},"doc://com.example.sit/documentation/App_SIT/ImageResource":{"navigatorTitle":[{"text":"ImageResource","kind":"identifier"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"ImageResource","kind":"identifier"}],"url":"\/documentation\/app_sit\/imageresource","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/ImageResource","title":"ImageResource","abstract":[{"text":"An image resource.","type":"text"}],"type":"topic","kind":"symbol"},"doc://com.example.sit/documentation/App_SIT/SwiftUICore":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/SwiftUICore","role":"collection","url":"\/documentation\/app_sit\/swiftuicore","kind":"symbol","title":"SwiftUICore"},"doc://com.example.sit/documentation/App_SIT/HomeScreenRouterProtocol":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"HomeScreenRouterProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeScreenRouterProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HomeScreenRouterProtocol"}],"type":"topic","url":"\/documentation\/app_sit\/homescreenrouterprotocol","title":"HomeScreenRouterProtocol","abstract":[]},"doc://com.example.sit/documentation/App_SIT/BASE_URL":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BASE_URL","type":"topic","role":"symbol","title":"BASE_URL","url":"\/documentation\/app_sit\/base_url","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"BASE_URL","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.example.sit/documentation/App_SIT/HomeViewModel":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewModel","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HomeViewModel","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HomeViewModel"}],"url":"\/documentation\/app_sit\/homeviewmodel","kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"HomeViewModel"},"doc://com.example.sit/documentation/App_SIT":{"role":"collection","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT","type":"topic","abstract":[],"url":"\/documentation\/app_sit","kind":"symbol","title":"App_SIT"},"doc://com.example.sit/documentation/App_SIT/ELauchScreenRouter":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/ELauchScreenRouter","type":"topic","role":"symbol","title":"ELauchScreenRouter","url":"\/documentation\/app_sit\/elauchscreenrouter","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ELauchScreenRouter"}],"kind":"symbol","navigatorTitle":[{"text":"ELauchScreenRouter","kind":"identifier"}]},"doc://com.example.sit/documentation/App_SIT/BaseViewController":{"role":"symbol","abstract":[{"type":"text","text":"Base ViewController for manage whole project UIViewController"}],"navigatorTitle":[{"text":"BaseViewController","kind":"identifier"}],"title":"BaseViewController","type":"topic","url":"\/documentation\/app_sit\/baseviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BaseViewController","kind":"identifier"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController","kind":"symbol"},"doc://com.example.sit/documentation/App_SIT/EViewController":{"url":"\/documentation\/app_sit\/eviewcontroller","title":"EViewController","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/EViewController","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"EViewController"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EViewController"}]},"doc://com.example.sit/documentation/App_SIT/LaunchScreenRouter":{"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenRouter","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LaunchScreenRouter"}],"navigatorTitle":[{"text":"LaunchScreenRouter","kind":"identifier"}],"url":"\/documentation\/app_sit\/launchscreenrouter","kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"LaunchScreenRouter"},"doc://com.example.sit/documentation/App-SIT/FeatureDocumentation":{"identifier":"doc:\/\/com.example.sit\/documentation\/App-SIT\/FeatureDocumentation","type":"topic","role":"collectionGroup","title":"Feature","url":"\/documentation\/app-sit\/featuredocumentation","abstract":[{"type":"text","text":"The "},{"code":"Feature","type":"codeVoice"},{"text":" module handles the Home Screen.","type":"text"}],"kind":"article"},"doc://com.example.sit/documentation/App-SIT/HomeDocumentation":{"identifier":"doc:\/\/com.example.sit\/documentation\/App-SIT\/HomeDocumentation","url":"\/documentation\/app-sit\/homedocumentation","kind":"article","role":"collectionGroup","abstract":[{"text":"The ","type":"text"},{"code":"Home Feature","type":"codeVoice"},{"type":"text","text":" module handles the Home Screen."}],"type":"topic","title":"Home Feature"},"doc://com.example.sit/documentation/App_SIT/EHomeScreenRouter":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EHomeScreenRouter"}],"title":"EHomeScreenRouter","type":"topic","url":"\/documentation\/app_sit\/ehomescreenrouter","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/EHomeScreenRouter","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"EHomeScreenRouter"}],"abstract":[],"role":"symbol"},"doc://com.example.sit/documentation/App_SIT/BaseTableViewCell":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BaseTableViewCell","kind":"identifier"}],"abstract":[],"url":"\/documentation\/app_sit\/basetableviewcell","type":"topic","navigatorTitle":[{"text":"BaseTableViewCell","kind":"identifier"}],"identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell","title":"BaseTableViewCell"},"doc://com.example.sit/documentation/App_SIT/HomeViewRouter":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HomeViewRouter"}],"type":"topic","abstract":[],"role":"symbol","title":"HomeViewRouter","identifier":"doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewRouter","url":"\/documentation\/app_sit\/homeviewrouter","navigatorTitle":[{"kind":"identifier","text":"HomeViewRouter"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"title":"Articles","identifiers":["doc:\/\/com.example.sit\/documentation\/App-SIT\/FeatureDocumentation","doc:\/\/com.example.sit\/documentation\/App-SIT\/HomeDocumentation"],"anchor":"Articles"},{"generated":true,"identifiers":["doc:\/\/com.example.sit\/documentation\/App_SIT\/AppDelegate","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableView","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseTableViewCell","doc:\/\/com.example.sit\/documentation\/App_SIT\/BaseViewController","doc:\/\/com.example.sit\/documentation\/App_SIT\/FeatureOneViewController","doc:\/\/com.example.sit\/documentation\/App_SIT\/HomeViewController","doc:\/\/com.example.sit\/documentation\/App_SIT\/LaunchScreenViewController","doc:\/\/com.example.sit\/documentation\/App_SIT\/LoadingViewController","doc:\/\/com.example.sit\/documentation\/App_SIT\/SceneDelegate","doc:\/\/com.example.sit\/documentation\/App_SIT\/TestingViewCell"],"anchor":"Classes","title":"Classes"}],"op":"replace"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController\/title","value":"LaunchScreenViewController"},{"value":[{"text":"LaunchScreenViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController\/fragments"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LaunchScreenViewController\/navigatorTitle","value":[{"text":"LaunchScreenViewController","kind":"identifier"}],"op":"replace"},{"value":"AppDelegate","op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate\/title"},{"value":[{"text":"AppDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1AppDelegate\/navigatorTitle","value":[{"text":"AppDelegate","kind":"identifier"}],"op":"replace"},{"value":"TestingViewCell","op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell\/fragments","value":[{"kind":"identifier","text":"TestingViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1TestingViewCell\/navigatorTitle","value":[{"text":"TestingViewCell","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1FeatureOneViewController\/title","op":"replace","value":"FeatureOneViewController"},{"op":"replace","value":[{"text":"FeatureOneViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1FeatureOneViewController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"FeatureOneViewController"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1FeatureOneViewController\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LoadingViewController\/title","op":"replace","value":"LoadingViewController"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LoadingViewController\/fragments","value":[{"text":"LoadingViewController","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"LoadingViewController"}],"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1LoadingViewController\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/title","value":"HomeViewController"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/fragments","value":[{"text":"HomeViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1HomeViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"HomeViewController"}]},{"value":"BaseTableView","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView\/fragments","value":[{"text":"BaseTableView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableView\/navigatorTitle","op":"replace","value":[{"text":"BaseTableView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate\/title","value":"SceneDelegate"},{"value":[{"kind":"identifier","text":"SceneDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate\/fragments"},{"value":[{"kind":"identifier","text":"SceneDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1SceneDelegate\/navigatorTitle"},{"value":"BaseViewController","op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController\/title"},{"value":[{"kind":"identifier","text":"BaseViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController\/fragments"},{"value":[{"text":"BaseViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseViewController\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableViewCell\/title","op":"replace","value":"BaseTableViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableViewCell\/fragments","value":[{"kind":"identifier","text":"BaseTableViewCell"}]},{"path":"\/references\/doc:~1~1com.example.sit~1documentation~1App_SIT~1BaseTableViewCell\/navigatorTitle","op":"replace","value":[{"text":"BaseTableViewCell","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}